### ISSUE TITLE
blue selection?

### ISSUE THREAD

**Issue by gabri25ele** [ALTaleX531/TranslucentFlyouts#10]
How is possible to have the blue selection like this
https://github.com/ALTaleX531/TranslucentFlyouts/blob/master/Images/popup_menu_sample_8.png

**Comment by ALTaleX531** [comment]
This is how the Windows 11 popup menu looks like when using TranslucentFlyouts, and if you're a pro you can do this by patching theme files without upgrading the system

**Comment by gabri25ele** [comment]
I used TranslucentFlyouts but any changes in color selction
let me know how

**Comment by Maplespe** [comment]
I guess this is caused by other third-party software such as StartAllBack (startisback)?

**Comment by ALTaleX531** [comment]
In fact, TranslucentFlyouts only changes the opacity of color selection, not the color itself

**Comment by gabri25ele** [comment]
> I guess this is caused by other third-party software such as StartAllBack (startisback)?

new operating system, clean at 100%

![Senza titolo](https://user-images.githubusercontent.com/33927879/206396351-da60718e-f3fd-49fa-b1fb-d552b622c84d.png)

**Comment by gabri25ele** [comment]
> In fact, TranslucentFlyouts only changes the opacity of color selection, not the color itself

so the thing you said before was not exact, the color can't be changed. 
blue can't come.

**Comment by gabri25ele** [comment]
> you can do this by patching theme files without upgrading the system

let me know how.

**Comment by ALTaleX531** [comment]
> > In fact, TranslucentFlyouts only changes the opacity of color selection, not the color itself
> 
> so the thing you said before was not exact, the color can't be changed. blue can't come.

Because I thought you were running Windows 10 at that time.The appearance of the popup menu is determined by theme file (such as background color, selection color), TranslucentFlyouts only  adds blur effect to the menu.The snapshot was taken in the older version of Windows 11, maybe MS changed something in the newer system.

**Comment by ALTaleX531** [comment]
> > you can do this by patching theme files without upgrading the system
> 
> let me know how.
![180855695-45bdb0fb-1c15-41f4-819a-37cfde9b93a7](https://user-images.githubusercontent.com/105535231/206496733-b4435537-8f59-45d4-bc5f-143352365367.png)
You can try mssstyleEditor, there are many related tutorials online.However, modifying the theme file may cause damage to your system.

**Comment by Poopooracoocoo** [comment]
>The snapshot was taken in the older version of Windows 11, maybe MS changed something in the newer system.

Yup. Microsoft made the highlight grey with Windows 11 22H2. Windows 11 is optional. 22H2 is also optional at the moment.
