### ISSUE TITLE
有点喜感的错误……

### ISSUE THREAD

**Issue by DellZHackintosh** [ALTaleX531/TranslucentFlyouts#101]
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/77269678/77d33441-a61b-40da-b9d4-ef8a494d205c)
我只是在5秒钟之内没有登录而已……😂

**Comment by scr0-0ge** [comment]
我也是，我还装了DWMBlurGlass 和 ExplorerBlurMica， 可能是冲突了吧

**Comment by ALTaleX531** [comment]
我可能确实没想到服务居然能比Windows 资源管理器先启动，如果你们资源管理器没事的话那就是检测写的不够严谨，没有什么兼容性问题

**Comment by shamodeyu** [comment]
我今天上午也遇到了这个问题。

**Comment by 120213404196** [comment]
所以说这种要怎么搞呀

**Comment by shamodeyu** [comment]
> 所以说这种要怎么搞呀

没处理，重启后再也没出现过。

**Comment by ALTaleX531** [comment]
下个版本应该会去除这个检测

**Comment by ALTaleX531** [comment]
请查看新版本

**Comment by DellZHackintosh** [comment]
但这个检测本身还是有意义的，去除不太好……

**Comment by ALTaleX531** [comment]
与其说是去除，不如说是引入了一个更有效的方案。在EnableMiniDump不为0的时候，会自动检测进程是否即将崩溃，如果是则创建内存转储文件，并提示用户是否中止TF防止循环崩溃。
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/e66c9a33-acb6-4f13-89e7-361d89748562)
（由于我的虚拟机是英文的镜像，所以显示语言是英文）
