### ISSUE TITLE
安装不了, 运行install.bat总会弹窗报错, Win11 Canary 最新版

### ISSUE THREAD

**Issue by chuck00000** [ALTaleX531/TranslucentFlyouts#104]
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/98159699/a6baefc5-387f-4b52-846e-cf9f8ef975b7)

**Comment by ALTaleX531** [comment]
你的CPU是不是不支持avx2指令集

**Comment by chuck00000** [comment]
> 你的CPU是不是不支持avx2指令集

是的，看了一下 不支持。 不支持就没法用了？

**Comment by ALTaleX531** [comment]
我发布的版本编译选项是启用了avx2指令集的，在你的机器上压根执行不了，如果你有能力可以尝试自己编译，或者等一下，我估计这周末应该能发布出一个新版本来解决这个问题。

**Comment by ALTaleX531** [comment]
请查看新版本
