### ISSUE TITLE
在文件资源管理器中右键压缩包文件时显示异常

### ISSUE THREAD

**Issue by 120213404196** [ALTaleX531/TranslucentFlyouts#106]
![屏幕截图 2024-03-05 140032](https://github.com/ALTaleX531/TranslucentFlyouts/assets/145527871/1498a610-92ad-4a0d-8932-82ceb42adde6)
![屏幕截图 2024-03-05 140011](https://github.com/ALTaleX531/TranslucentFlyouts/assets/145527871/474b3220-ef55-401a-a11a-06b0989eb367)

**Comment by ALTaleX531** [comment]
升级你的ExplorerBlurMica后重新测试

**Comment by 13236812329** [comment]
我升级了这个3.0
![屏幕截图 2024-03-05 143223](https://github.com/ALTaleX531/TranslucentFlyouts/assets/145527871/fbcebba1-270b-4ba0-9324-83586c5c01f9)

**Comment by 13236812329** [comment]
还是这样，就只有压缩包类文件右键时会这样

**Comment by ALTaleX531** [comment]
也安了bandizip，没发现有什么问题，建议把ExplorerBlurMica停了再测试一下

**Comment by 120213404196** [comment]
ExplorerBlurMica是啥呀

**Comment by 120213404196** [comment]
枫の主题社？

**Comment by ALTaleX531** [comment]
是的，这个错位的问题我只在它那发现过

**Comment by 120213404196** [comment]
v2时候还好，更新V3后文件资源管理器还崩溃了

**Comment by 120213404196** [comment]
都是因为和它冲突了吧

**Comment by ALTaleX531** [comment]
#98 修复了崩溃问题，v2确实有冲突，而且你这工具箱版本估计很老了

**Comment by 120213404196** [comment]
确实1.1.1版本的，更新一下枫是不是就可以解决了

**Comment by ALTaleX531** [comment]
应该是的，但是更了之后就必须要用v3了

**Comment by 120213404196** [comment]
okok

**Comment by 120213404196** [comment]
感谢感谢
