### ISSUE TITLE
[Bug] Fluent Animation doesn't animate the border

### ISSUE THREAD

**Issue by emvaized** [ALTaleX531/TranslucentFlyouts#108]
When "Fluent Animation" is enabled (set to default "slide" animation), popup border doesn't get animated and just appears in the air: 

![2024-03-07172204-ezgif com-video-to-gif-converter](https://github.com/ALTaleX531/TranslucentFlyouts/assets/37851576/fd2ad46e-3e20-4514-9c56-42180527b9a8)

Version: TranslucentFlyouts.V3.x64_20240125_Updated

**Comment by ALTaleX531** [comment]
Duplicate of #39. It's not a bug and can't be fixed

**Comment by emvaized** [comment]
Okay, got it! Thanks

**Comment by TechySC23** [comment]
Hey! Have you used Satanarious's GUI for configuring this? Link: https://github.com/Satanarious/TranslucentFlyoutsConfig/releases/tag/v1.3.3 Now once you've opened that, go to settings then set the install location to the TFv3 directory. Ok, now all the prerequisites are done! Now go back to the normal page and select the Global tab. Now go to the "No border-color" option and select "Yes". Then click apply. Simple and Easy! [P.S: If it's still not working then restart explorer.]

**Comment by emvaized** [comment]
@TechySC23 
Yeah, if only "No border-color" solved the problem...

https://github.com/ALTaleX531/TranslucentFlyouts/assets/37851576/d292eb2c-9208-473f-8011-ec5f112bc75e

**Comment by TechySC23** [comment]
> @TechySC23 Yeah, if only "No border color" solved the problem...
> 2024-03-09.192039.mp4

Ah sh*t. Have you tried tinkering with Pop in time, Fade-in, and fade-out time? But the "No border-color" option helped with that. And the pop-in ratio, also do you have Start11 or StartAllBack? ALTaleX said that Start11 messes with that. Wait why do you have MicaForEveryone? Try disabling that.

**Comment by ALTaleX531** [comment]
As I said, it can't be fixed, and even with `NoBorderColor` enabled, there's still a drop shadow remaining unless you turn off rounded corners.

**Comment by TechySC23** [comment]
Wait, wdym with rounded corners?

**Comment by ALTaleX531** [comment]
@TechySC23 
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/611a880a-4990-4d4c-823b-793e855593d2)

**Comment by TechySC23** [comment]
send an video

**Comment by ALTaleX531** [comment]
@TechySC23 Here you go
https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/25f35717-f495-4268-97ee-83950566d803

**Comment by TechySC23** [comment]
K. Now use it with all the different animations

**Comment by XiaoTDM** [comment]
EN:
I think this issue can be fixed like this:
Disable menu shadows while the animation is playing, until the animation is finished.
In fact, the original Win UI menu is handled in the same way.

CH:
我觉得这个问题可以这样处理：
当动画播放时禁用阴影，当播放完成后再启用。
实际上 Win UI 原生菜单也是这么处理的。

**Comment by ALTaleX531** [comment]
@XiaoTDM 答案是做不到，只要你用了DWMAPI指定了菜单有圆角，那么DWM必定会给你渲染一个阴影，没有任何办法去除掉，WinUI这样能行的基础建立于所有的内容的绘制都走Windows.UI.Composition，不依靠DWMAPI。然而本身菜单的渲染都是GDI完成的，只有通过DWMAPI才能实现更高级的特性，比如透明，圆角。对于[Shell](https://github.com/moudey/Shell)这样推倒一切重头再来的是可能的，但代价就是产生了各种各样的问题。基本上你们能想到的，我都试了一遍，可惜都没有用。
