### ISSUE TITLE
[Enhancement or New Feature?] [Request] Context menu DPI scaling customization

### ISSUE THREAD

**Issue by TechySC23** [ALTaleX531/TranslucentFlyouts#110]
So I've seen that the Win Right click menu (Default) is dependent on the scaling option in Windows. But as Microsoft nuked the classic context menu, the old one doesn't follow the orders of either the Resolution or Scaling option. And as I'm a user who changes the default res (FHD) to 1440p, it irritates me... A LOT! So, please, please try to make a size option. And I need the option in the GUI, Please 🙏 @Satanarious

**Comment by ALTaleX531** [comment]
The classic context menu has always been DPI-aware, I'm not sure exactly what's wrong with it, maybe some screenshots would help.

**Comment by TechySC23** [comment]
Here they are:
![Screenshot 2024-03-09 161823](https://github.com/ALTaleX531/TranslucentFlyouts/assets/138615236/761586af-fe7b-4e8d-a865-f2414bb5a9f5)
![Screenshot 2024-03-09 162529](https://github.com/ALTaleX531/TranslucentFlyouts/assets/138615236/63aa2ee5-fe02-413b-b798-a763a327ce28)

**Comment by ALTaleX531** [comment]
I think the classic context menu behaves normally, the reason for the larger immersive menu items and text is to optimize the touch experience.

**Comment by ALTaleX531** [comment]
Unfortunately this feature is not possible with TranslucentFlyouts, I can only change the size of the item but not the size of the text.

**Comment by TechySC23** [comment]
@ALTaleX531 No problem man. I appreciate that you built this project, But I thought it would be with the monitor's scaling. But anyways just few days ago I downloaded the TF v3 Insider preview. Now just 3 hours ago you released the v3. So?? How do I update it? I don't wanna uninstall all the config. And I checked that Satanarious's Config's Run button doesn't work anymore.

**Comment by TechySC23** [comment]
@ALTaleX531 Satanarious's Config doesn't have all the features that TF has. So does that mean I have to do it manually?

**Comment by ALTaleX531** [comment]
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/8e8794b8-002f-4ace-a787-3703b4588c0e)
Run the uninstall_win32.bat, click "No", then your config information will be preserved. And then run the install script again. The old features can still be tweaked via the GUI, but the new ones need to wait for him to support them or manually create specific registry items. But I bet you don't need those new features.

**Comment by Satanarious** [comment]
> @ALTaleX531 No problem man. I appreciate that you built this project, But I thought it would be with the monitor's scaling. But anyways just few days ago I downloaded the TF v3 Insider preview. Now just 3 hours ago you released the v3. So?? How do I update it? I don't wanna uninstall all the config. And I checked that Satanarious's Config's Run button doesn't work anymore.   

I disabled the run button because of one of the recent updates, before v3.0 had the run.bat file missing

**Comment by Satanarious** [comment]
> @ALTaleX531 Satanarious's Config doesn't have all the features that TF has. So does that mean I have to do it manually?

I'm working on something else right now, I'll start working on it soon. Unfortunately you'll have to do it manually for the time being.

**Comment by ALTaleX531** [comment]
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/7844a82a-a89d-4707-b049-8464a597359d)
@Satanarious  I've exported these APIs in C style, no need to manipulate them through scripts...
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/9a383c43-650c-4749-b1af-6a3e219d629b)

**Comment by Satanarious** [comment]
> ![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/7844a82a-a89d-4707-b049-8464a597359d)
> @Satanarious  I've exported these APIs in C style, no need to manipulate them through scripts...
> ![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/9a383c43-650c-4749-b1af-6a3e219d629b)
> 

Correct me if I'm wrong, So you can now start/stop/install/uninstall TFs by changing a value in the registry.

**Comment by ALTaleX531** [comment]
@Satanarious No, here is an example of using StopService.
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/a7cadba9-4a49-45ab-ba6b-8e4c12993697)
BTW: After using StartService you need to create a message loop using the Win32 API GetMessageW, otherwise it won't work properly. Another easy way is to call rundll32 as the script does.

**Comment by Satanarious** [comment]
> @Satanarious No, here is an example of using StopService.
> ![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/a7cadba9-4a49-45ab-ba6b-8e4c12993697)
> BTW: ~~After using StartService you need to create a message loop using the Win32 API GetMessageW, otherwise it won't work properly.~~ Another easy way is to call rundll32 as the script does.

Oh okay, that makes it clear. I'll look into it.

**Comment by TechySC23** [comment]
So you guys fixed it? I got offline for a sec:)

**Comment by TechySC23** [comment]
> ![image](https://private-user-images.githubusercontent.com/105535231/311437122-8e8794b8-002f-4ace-a787-3703b4588c0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTMwNzQsIm5iZiI6MTcwOTk5Mjc3NCwicGF0aCI6Ii8xMDU1MzUyMzEvMzExNDM3MTIyLThlODc5NGI4LTAwMmYtNGFjZS1hNzg3LTM3MDNiNDU4OGMwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQxMzU5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTZlMDE2ZGI3M2FhN2Y4MzEwYWY5OGRmZjlmMGFkMDg5Y2EyMWFlMmZkYTM3NzMyNTBlMTM3NzJkZmRlYTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GMUtQpLmohJCq18F0XWNd_GXUHAhK-HoStw83cwbYoM) Run the uninstall_win32.bat, click "No", then your config information will be preserved. And then run the install script again. The old features can still be tweaked via the GUI, but the new ones need to wait for him to support them or manually create specific registry items. But I bet you don't need those new features.

Thanks
