### ISSUE TITLE
Fluent Animations not working since v2.1.0

### ISSUE THREAD

**Issue by TechySC23** [ALTaleX531/TranslucentFlyouts#114]

**Comment by ALTaleX531** [comment]
Tested without this issue, please provide more information.

**Comment by TechySC23** [comment]
So on my machine, I tested the animations since v2.1.0. They just are stuck in the default animation. Mind you I have: Custom Rendering-on, Fluent Animations-on.

**Comment by TechySC23** [comment]
@ALTaleX531 How is this completed?

**Comment by TechySC23** [comment]
Is #115 Related to this? I think because, without Custom Rendering and Fluent animations, animations just can't happen. But in my case, the custom rendering is on because I know the difference between the vanilla Win menu (Win 10- version) and the custom one
