### ISSUE TITLE
coordination of menu graphics

### ISSUE THREAD

**Issue by Au-angeloupali** [ALTaleX531/TranslucentFlyouts#117]
Could it be possible in future versions to standardize the first menu that appears with the right mouse click and the menu configured with translucentflayout?

menu graphics on right mouse click
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/118266752/8211d16d-60cb-4c79-b24e-7f1ee3be7415)

graphics menu clicking show more options configured with translucentflayout
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/118266752/70d120cf-75c6-4df3-8c11-aba75e7173a9)

I also notice that programs like Illustrator have the correct menu graphics, while some like Photoshop keep the ugly one by default. Is there a way to fix this too?

![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/118266752/dbef6994-c1d2-4be3-a4cf-b15db9cf050e)
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/118266752/b108a36c-c1ff-43e1-b4a0-a0f00db22432)

thanks, great work anyway

**Comment by TechySC23** [comment]
@Au-angeloupali Use the menu option in the GUI of Satanarious—link in the repo's README. The menu option will help to resolve these old, 2010-era menus!😄

**Comment by Au-angeloupali** [comment]
@TechySC23 I tried as you told me, but it can only take some of the options.

for example I set the focusing color, but it can't pick it up... same thing for the corner radius

![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/118266752/ce92ecdd-af88-4113-b17e-78d09e6f9647)

by setting all the options the Photoshop menu remains the old one.

**Comment by Satanarious** [comment]
So, I was trying to fix the internal function in TFC, when I noticed that after I installed and uninstalled TF multiple times in a row. The Menu section stopped having any effect on Menus (Registry value changes make no difference) on:
- Desktop Context Menu
- Taskbar Context Menu
- File Context Menus
- Directory Context Menus

Working on:
- Window Titlebars Context Menu
- Recycle Bin Items Context Menu

This includes everything in the Menu section, from Animations to Separator. I noticed that these flyouts reverted back to their default settings.

![TFbug](https://github.com/ALTaleX531/TranslucentFlyouts/assets/42642682/7a4f46fa-e236-4e58-bdc4-e541a66d047b)

**Comment by ALTaleX531** [comment]
@Au-angeloupali If you want the icons of the classic context menus to be synchronized with the icons of the immersive menus, I think that's far beyond the scope of "translucenct", which should be implemented by [Shell](https://github.com/moudey/Shell).

Photoshop's menus are leftovers from Windows 2000, and its rendering process is handled by the kernel, which is not something I can take over rendering. As to why Adobe's softwares use different styles, you should ask Adobe, I don't know why.

**Comment by ALTaleX531** [comment]
They are not compatible and if you wish to combine them together then you need to repeat the steps in #109.

**Comment by Satanarious** [comment]
> @Satanarious [TranslucentFlyouts.Win32.V3.x64.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/14605311/TranslucentFlyouts.Win32.V3.x64.zip) Please try this build to see if it solves the problem.

I'm sorry, I cannot reproduce the bug. Someone mentioned in an issue on my repo that they were having problems in the Menu section. I played around a bit with install/uninstall/run/stop and it somehow happened. Now even though I'm using v3.0.1 and not the one you sent, I cannot reproduce the bug.

**Comment by ALTaleX531** [comment]
The issue seems to have been resolved.
