### ISSUE TITLE
Error on launch of moddded Baldurs Gate 3

### ISSUE THREAD

**Issue by PrincessAkira** [ALTaleX531/TranslucentFlyouts#121]
When im launching it normally it will display nothing.
When launching via mod launcher it will display an Error and not even crash.

![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/45071533/ccc1fd6c-e88e-4297-bd57-c281c31dc1fa)

Video here
https://github.com/ALTaleX531/TranslucentFlyouts/assets/45071533/f656c9a9-1548-4bc4-ae84-064dfdad8524

**Comment by ALTaleX531** [comment]
You can avoid this problem by adding the game's process name to the DisabledList in the latest version, see #109. Also, providing memory dump file helps a lot in solving this problem.

**Comment by ALTaleX531** [comment]
It looks like you've solved the problem, but I'd appreciate it if you could provide the dump file to help troubleshoot the root cause of the problem.
