### ISSUE TITLE
change the color of menu items

### ISSUE THREAD

**Issue by Au-angeloupali** [ALTaleX531/TranslucentFlyouts#123]
everything works great now, you may in the next version have the ability to change the colors of the menu items, for example selectable menu item, non-selectable menu item and hot menu item

**Comment by ALTaleX531** [comment]
These options have always been customizable since v2, you just don't know how to do it.

**Comment by Au-angeloupali** [comment]
@ALTaleX531 I searched everywhere even in the history of old versions but I can't find how to set it. Where should I look?

**Comment by Au-angeloupali** [comment]
No okay i've already set this. I mean the color of the written, in this case for example from white to black

![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/118266752/c597d715-000d-4d7c-b133-408dac1e57eb)

**Comment by ALTaleX531** [comment]
Alternatively, set your color mode to light mode.

**Comment by Au-angeloupali** [comment]
So is impossible to make a similar condition?
With the hot colored written in a different color

![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/118266752/5b7822ac-bd93-49ab-9761-7c8f9a88e424)

**Comment by ALTaleX531** [comment]
This is where third-party themes come into play, and this should not be implemented in a program that introduces transparency features.

**Comment by Au-angeloupali** [comment]
okay I understand and thank you for the clarity.
Just for information, the nemu that I posted to you is that of the application at the link below. it works really well.

Thanks again, Angelo.

https://www.mydockfinder.com/
