### ISSUE TITLE
AVG causes Win64:Malware-Gen virus/trojan alert 

### ISSUE THREAD

**Issue by Sabbath1977** [ALTaleX531/TranslucentFlyouts#13]
Dear ALTaleX531,

AVG virus scanner inhibits download/use of **Win64:Malware-Gen** d/t virus/trojan detection algorithm triggerd.

Thanks for your great work and contribution to the github community. 

Brgds, Sabbath1977

**Comment by ALTaleX531** [comment]
![screenshot_of_translucent_slideouts_warning](https://user-images.githubusercontent.com/105535231/206711469-aef47ae0-c677-4b9a-8819-90f845757be4.jpg)
It will not be fixed. There is no way TranslucentFlyouts can be completely "secure". If you don't trust the released build, you can compile the code yourself. Any other questions?

**Comment by Sabbath1977** [comment]
... you may report it here in order to get excluded from false-positive trojan detection (**Win64:Malware-Gen** is nothing easily to be ignored):

https://www.avg.com/en-ww/false-positive-file-form#pc

Thanks and clofi :-)

**Comment by ALTaleX531** [comment]
![feedback](https://user-images.githubusercontent.com/105535231/206732897-f5c3e616-6773-44b4-9c2c-ca265495f6dc.png)
I have already reported this. However, you know that false-positive trojan detection is sometimes unavoidable

**Comment by ALTaleX531** [comment]
![6%$XA5C}(5OG1{V)TSN2GQN](https://user-images.githubusercontent.com/105535231/206827169-154b995d-14f5-4882-b2a2-83e9a5c151a7.png)
I guess the issue is solved now.
