### ISSUE TITLE
Separate animation for dropdown/sub-menu flyouts?

### ISSUE THREAD

**Issue by Arin-426** [ALTaleX531/TranslucentFlyouts#132]
I don't really use Github much, so forgive me for any mistakes.

Anyway, I am trying to configure separate animation for the drop-down menus, how do I do that? (the ones that shows up when you hover over "View", "Sort by", "New" options in the right click menu).

Currently, I have set the animation of right click menu to be Scroll Zoom, but I'd like to set the animation of the sub-menus, drop-down menus to be Ripple. How do I do that? Is it even possible?

Thank you.

**Comment by ALTaleX531** [comment]
You can't specify different animations for different menus, and by the way DropDown and Menu aren't the same thing, the former is what pops up when you click the ">" button in the address bar of the file explorer.
