### ISSUE TITLE
Windows Insider version does NOT WORK!

### ISSUE THREAD

**Issue by TechySC23** [ALTaleX531/TranslucentFlyouts#137]

**Comment by TechySC23** [comment]
So I recently upgraded to the release preview version of Windows 11. And decided to install the latest version of TF v3.1.1. And the symbols just don't install, why?
\

**Comment by bbmaster123** [comment]
look here: https://github.com/Maplespe/DWMBlurGlass/discussions/223
Symbols only become available publicly for release builds of windows. Symbols must match exactly the build you are currently running. This is the same for any app that relies on symbols to work correctly.
Hope that explains it, cheers

**Comment by ALTaleX531** [comment]
I've mentioned this many times before, check out the previous issues.
For those of you who like to try out the pre-release version of Windows, I recommend always setting `EnableCompatibilityMode` to 1. Any features involving symbols are difficult to work properly on the latest Windows.

**Comment by TechySC23** [comment]
> I've mentioned this many times before, check out the previous issues. For those of you who like to try out the pre-release version of Windows, I recommend always setting `EnableCompatibilityMode` to 1. Any features involving symbols are difficult to work properly on the latest Windows.

@ALTaleX531 I used that compat mode but two things happened:
1. No transparency (or translucency)
2. Only animation visually applied
