### ISSUE TITLE
Waht is "UI settings auto run" for?

### ISSUE THREAD

**Issue by 1di9** [ALTaleX531/TranslucentFlyouts#14]
If checked or unchecked nothing's change.
Is it possible to start TranslucentFlyoutGui.exe minimized?

**Comment by ALTaleX531** [comment]
I think you should reboot after making TranslucentFlyouts auto run and see what will happen.

**Comment by 1di9** [comment]
Nothing happen when I reboot Windows even if i checked auto run.
Progran don't auto run. I have to put a link into autorun folder, but It start everytime windowed and not mininized.
Il 12 dic 2022, 16:11 +0100, ALTaleX531 ***@***.***>, ha scritto:

**Comment by ALTaleX531** [comment]
That's kind of weird. I have tested it today and it worked fine. Maybe this was caused by a anti-virus software. 
Another way to start it minisized is adding a parameter "/onboot" to the commandline.
