### ISSUE TITLE
TranslucentFlyouts doesn't support newest Windows 11 update

### ISSUE THREAD

**Issue by borsuczyna** [ALTaleX531/TranslucentFlyouts#140]
Windows version: Windows 11 Home 24H2 26120.461

[MenuHandler] It appears that you are running TranslucentFlyouts on an UNSUPPORTED Windows system! The symbol file was loaded successfully but resolved failed, please report your OS information to developer!
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/65825775/578dbbcf-346e-4f88-ae4f-684207c23ad6)

**Comment by ALTaleX531** [comment]
https://github.com/ALTaleX531/TranslucentFlyouts/issues/145#issuecomment-2184123075
