### ISSUE TITLE
bandizip右键预览压缩文件内容异常

### ISSUE THREAD

**Issue by AquaHarp** [ALTaleX531/TranslucentFlyouts#143]
Win11 23H2 22631.3593，Bandizip 6.29，DWMBlurGlass 2.2.0 。
TranslucentFlyouts v3.1.1 ， 右击管理员运行install_win32.bat安装
关闭“预览压缩文件”功能问题就消失了
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/25244319/87e16490-1a6f-47dc-977f-557dd575f1a1)

浅色模式：
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/25244319/9d691afe-f155-4dd3-9f05-891d764fe71c)

深色模式：
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/25244319/8a69e8f2-e915-47a8-94a2-56c6a3a17368)

**Comment by ALTaleX531** [comment]
修不了，Bandizip的这个预览是自己渲染的，不支持透明，我接管不了
