### ISSUE TITLE
Error occured while loading symbols

### ISSUE THREAD

**Issue by Andrew-Sor** [ALTaleX531/TranslucentFlyouts#145]
Every time I start Windows I see this console.
![image_2024-06-08_09-37-37](https://github.com/ALTaleX531/TranslucentFlyouts/assets/133566800/59d4c66e-f76c-49ef-97c9-79e51c0c84b7)
It seems to say that I do not have an Internet connection, although this is not true
How to fix it?

**Comment by ALTaleX531** [comment]
It looks like you are on 24H2, setting `HKEY_CURRENT_USER\Software\TranslucentFlyouts\Menu\NoModernAppBackgroundColor` to 0 can fix this.

**Comment by Andrew-Sor** [comment]
> It looks like you are on 24H2, setting `HKEY_CURRENT_USER\Software\TranslucentFlyouts\Menu\NoModernAppBackgroundColor` to 0 can fix this.

Thanks
