### ISSUE TITLE
Preventing trying to download symbols at Windws startup

### ISSUE THREAD

**Issue by 03302024** [ALTaleX531/TranslucentFlyouts#147]
I installed the app, but not the symbols, as I couldn't download them, and offline installation is deactivated.

At the end, I got transparent menus working. However, after a Windows restart, I again was asked for symbols download. How I could prevent that (trying to download symbols) at Windws startup?

**Comment by ALTaleX531** [comment]
[disable_internet_connection]https://github.com/ALTaleX531/TranslucentFlyouts/files/14159185/disable_internet_connection.zip

**Comment by 03302024** [comment]
Thank you. It works.
