### ISSUE TITLE
Transparent menus on desktop, but not on Windows File Explorer

### ISSUE THREAD

**Issue by 03302024** [ALTaleX531/TranslucentFlyouts#149]
I like transparent menus on desktop, but not so on Windows File Explorer. 

So, I added "explorer.exe" to "Disabled List", but the side effect was that the desktop transparent menus were also gone. Is there a remedy for this?

**Comment by ALTaleX531** [comment]
No, it is impossible. Desktop and file explorer are the same process.

**Comment by 03302024** [comment]
Can't you use the Windows File Explorer window handle number to get its process number, and go from there, rather than using the generic "explorer.exe" process name?
