### ISSUE TITLE
TranslucentFlyouts causes text to not render properly in Control Panel

### ISSUE THREAD

**Issue by ice051128** [ALTaleX531/TranslucentFlyouts#15]
The app causes the menu text to not render properly on windows 10. See screenshot for issue.

![Screenshot_1](https://user-images.githubusercontent.com/49018832/207041880-ee60d7a9-67b2-4b23-afd1-dbcfd53a5416.png)

**Comment by ALTaleX531** [comment]
I think it is not about text, but background.

**Comment by ALTaleX531** [comment]
I have tested it just now and it worked fine.  Could you show me the steps to reproduce the problem?

**Comment by ice051128** [comment]
> I have tested it just now and it worked fine. Could you show me the steps to reproduce the problem?

U just open it up and it's there

**Comment by ALTaleX531** [comment]
![1670946216961](https://user-images.githubusercontent.com/105535231/207382546-c782cf9d-d4f6-41a0-a0ac-cbd9f8c12a0a.png)
 Maybe it was caused by other third-party software? As you can see, everything is normal up there.

**Comment by ALTaleX531** [comment]
I have confirmed that this issue is caused by [ExplorerBlurMica](https://github.com/Maplespe/ExplorerBlurMica). Also, I don't recommend using these two apps together, as explorer may crash in some cases.
