### ISSUE TITLE
额……作用良好？

### ISSUE THREAD

**Issue by Lukoning** [ALTaleX531/TranslucentFlyouts#151]
某些背景效果会“**随机**”导致菜单背景完全透明
比如：
![屏幕截图 2024-07-01 164638](https://github.com/ALTaleX531/TranslucentFlyouts/assets/92252063/91854395-3271-43e5-8158-c941cac889b1)
![屏幕截图 2024-07-01 164623](https://github.com/ALTaleX531/TranslucentFlyouts/assets/92252063/f70cfa15-0757-481f-9301-b303dfe468b7)

以及（这里不重复放生效成功的了）
![屏幕截图 2024-07-01 164708](https://github.com/ALTaleX531/TranslucentFlyouts/assets/92252063/3f277ac1-afa3-4121-a65e-3e1bd65b9743)
![屏幕截图 2024-07-01 164730](https://github.com/ALTaleX531/TranslucentFlyouts/assets/92252063/0ac716d1-914c-43f4-ad40-4eb009c0c64d)

符号文件正常
Windows版本10.0.22631.3810
系统更新前也有这个bug，应该不是更新造成的

**Comment by XiaoTDM** [comment]
这边系统更新的可能也不小，我是更新后出现这个bug的。
甚至ExplorerPatcher的改版任务栏右键菜单直接永久全透明

**Comment by ALTaleX531** [comment]
EffectType=3已经在22621之后被微软删除，其它的我测试过22631是没有问题的，你可能安了DWMBlurGlass并启用了覆盖accent

**Comment by Lukoning** [comment]
> EffectType=3已经在22621之后被微软删除，其它的我测试过22631是没有问题的，你可能安了DWMBlurGlass并启用了覆盖accent

啊，确实，关闭覆盖Accent后就解决了
