### ISSUE TITLE
Hide from system tray?

### ISSUE THREAD

**Issue by ice051128** [ALTaleX531/TranslucentFlyouts#16]
Is it possible to make it hide from the system tray so it looks more integrated with windows?

![image](https://user-images.githubusercontent.com/49018832/207229803-c1c5767e-9635-463f-a3ba-f9f5ef8c762b.png)

**Comment by ALTaleX531** [comment]
For now, there is no way to hide it since you can't exit the app if the tray icon disappears. Maybe it will be available in the next version.

**Comment by ice051128** [comment]
> For now, there is no way to hide it since you can't exit the app if the tray icon disappears. Maybe it will be available in the next version.

U can already exit the app with task manager tho? It's better to be able to hide it from the system tray especially with this kind of system tweaks where u just set it up and forget about it. Makes it look and feel more seamless

**Comment by ALTaleX531** [comment]
However, exit the app by terminating process is not recommended and it may cause problems. In the next release, tray icon and notifications will be optional.

**Comment by ALTaleX531** [comment]
However, exit the app by terminating process is not recommended and it may cause problems. In the next release, tray icon and notifications will be optional.

**Comment by wzheyo** [comment]
I also recommend adding an option to hide tray icon. Users can choose according to their needs.Thanks to the developers.

**Comment by ALTaleX531** [comment]
Outdated issue, close now...
