### ISSUE TITLE
Can this app apply this effect to explorer window? Run window? etc

### ISSUE THREAD

**Issue by drakulaboy** [ALTaleX531/TranslucentFlyouts#17]
as title says, is it possible?

**Comment by ALTaleX531** [comment]
I think you are looking for [https://github.com/Maplespe/ExplorerBlurMica](url), which adds blur to explorer window. However, TranslucentFlyouts may not work well with it, since it use the same text rendering layer.In the future, maybe this app can apply effect to run window or message box.

**Comment by drakulaboy** [comment]
wow, didn't know about that ExplorerBlur, thank you very much! If it's not hard will be awesome to have the option to apply blur to explorer stuff

**Comment by e-t-l** [comment]
@drakulaboy I'm interested to hear if you ever tried installing ExplorerBlurMica alongside TF, and if they work well running simultaneously!

**Comment by ALTaleX531** [comment]
> @drakulaboy I'm interested to hear if you ever tried installing ExplorerBlurMica alongside TF, and if they work well running simultaneously!

Since TF v2, you can use ExplorerBlurMica with TF without any problem.
