### ISSUE TITLE
black background on Acrobat's menu

### ISSUE THREAD

**Issue by shamodeyu** [ALTaleX531/TranslucentFlyouts#18]
默认设置的情况下，Acrobat的菜单栏是黑色的，Windows 10和11都出现同样问题。
![bug](https://user-images.githubusercontent.com/123850195/215302146-cee13e3d-4209-44c5-b989-e6f10693a6cd.png)
尝试修改其他设置，无效。

**Comment by ALTaleX531** [comment]
![image](https://user-images.githubusercontent.com/105535231/215303108-e7a214a1-6646-42a5-9175-02a5bedcf538.png)
请问您的版本是什么，最新版似乎没有这个问题。

**Comment by shamodeyu** [comment]
Pro DC 64位 2022.001.20085.

**Comment by ALTaleX531** [comment]
我倾向于Acrobat本身没有正确处理亮暗的切换，而TranslucentFlyouts不知道怎么干扰到了Acrobat颜色模式的切换，只要Acrobat在TranslucentFlyouts之后运行必定会出现此问题。TranslucentFlyouts现在正在重构代码，而我最近比较忙碌，您可能需要等上比较长的时间

**Comment by shamodeyu** [comment]
我也注意到先打开Acrobat，再开启TranslucentFlyouts，就没有黑色背景。目前先这么临时对策。
您先重构，期待新版！

**Comment by shamodeyu** [comment]
还是Acrobat，标签里的标题在启用TranslucentFlyouts前后发生变化。

启用前
![2023-02-17 16 05 58](https://user-images.githubusercontent.com/123850195/219588038-4d6b1c52-31da-4294-8fdd-41d7b997cef8.png)

启用后
![2023-02-17 16 07 00](https://user-images.githubusercontent.com/123850195/219588050-66bb8dea-6c8a-4047-adb7-2e67a18bcdf2.png)
