### ISSUE TITLE
标签里的标题在启用TranslucentFlyouts前后发生变化

### ISSUE THREAD

**Issue by shamodeyu** [ALTaleX531/TranslucentFlyouts#19]
还是Acrobat，标签里的标题在启用TranslucentFlyouts前后发生变化。

启用前
![2023-02-17 16 05 58](https://user-images.githubusercontent.com/123850195/219588529-5f1417d0-3a8c-4074-84c3-78f96614dfe4.png)

启用后
![2023-02-17 16 07 00](https://user-images.githubusercontent.com/123850195/219588565-d8d4becd-834f-4aa4-9993-a5270a0e9cd0.png)

**Comment by ALTaleX531** [comment]
TranslucentFlyouts又接管了它无需负责的文字渲染，旧版的话我先想想办法，重置版可以说已经是完全解决了这类问题
