### ISSUE TITLE
[CSP軟體顯示出錯]

### ISSUE THREAD

**Issue by Qyuanan** [ALTaleX531/TranslucentFlyouts#20]
開啓TranslucentFlyouts的彈出菜單功能後會出現CSP軟體内工具以及相關選項文字消失
(害的幾天都沒法用)XD 
相關可參考我發佈的這個提問
[https://ask.clip-studio.com/zh-tw/detail?id=89172](url)

**Comment by ALTaleX531** [comment]
这其实和 #19 的那个BUG是同源的，重构版已经完全解决了这一问题，但可能需要比较长的时间才能发布
如果您只需要资源管理器的菜单是亚克力的，您可以暂时先用AcrylicMenus，一个基于TranslucentFlyouts的优化版
还是很抱歉TranslucentFlyouts没能达到您预期的效果，我会尽快解决此问题的

**Comment by ALTaleX531** [comment]
#22 新版本在此测试 :)

**Comment by ALTaleX531** [comment]
[新版本已发布](https://github.com/ALTaleX531/TranslucentFlyouts/releases/tag/v2.0.0-alpha)
