### ISSUE TITLE
导致系统故障

### ISSUE THREAD

**Issue by shamodeyu** [ALTaleX531/TranslucentFlyouts#21]
Win10 64位，近期常有无法打开cad程序和文件的情况，以及锁屏后无法使用Ctrl+Alt+Del调出登陆对话框以便输入登陆密码的情况。
回忆了一下，可能是使用本软件后发生的。

不使用本软件，经重启系统多次试验，暂未发现无法打开cad文件、无法调出登陆对话框的情况。

当然，我的问题可能是个案，不具代表性。

**Comment by ALTaleX531** [comment]
感谢你的反馈，虽然我认为从根本上TranslucentFlyouts不具备干预登录屏幕的权限，也无法干预文件的读写，所以也请你检查一下是否是近期安装的其它软件的问题。周末如果可以的话，我会进行重置版的测试，也请你提提意见和反馈一下Bug。本软件完全是个人在业余时间开发的，所以更新的没办法很勤，也希望多多见谅

**Comment by shamodeyu** [comment]
因为我不熟悉软件开发，可能有所误解。期待新版本。

**Comment by ALTaleX531** [comment]
预计这个周末吧

**Comment by ALTaleX531** [comment]
[TranslucentFlyouts-Remake.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/10891322/TranslucentFlyouts-Remake.zip)

重置版，进行初步测试，所以当前不能直接更改参数，也不可在生产环境中使用。运行test.exe启动TranslucentFlyouts，其中附带了动画组件，如果不需要可以移除
如果重置版能修复相关bug或导致新的bug，请及时告诉我

**Comment by shamodeyu** [comment]
![2023-03-05 16 33 01](https://user-images.githubusercontent.com/123850195/222950294-bd2efdba-86ac-46c5-b5de-f0d118308bfd.png)

**Comment by ALTaleX531** [comment]
[TranslucentFlyouts-Remake.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/10891390/TranslucentFlyouts-Remake.zip)

**Comment by shamodeyu** [comment]
![2023-03-06 08 09 53](https://user-images.githubusercontent.com/123850195/222994311-0194762d-0230-45eb-8faa-e079a55a3968.png)
![2023-03-06 08 11 50](https://user-images.githubusercontent.com/123850195/222994317-3f99ee1f-9408-4cf7-a247-01b4d5c6c5c1.png)

**Comment by ALTaleX531** [comment]
尝试删除TFAnimator.dll后继续测试，我在多台电脑上测试都未出现没出现内容的情况

**Comment by ALTaleX531** [comment]
记得不可与旧版同时运行

**Comment by shamodeyu** [comment]
1. 删去TFAnimator64.dll后，右键单击，鼠标滑过有下级菜单的项目时，下级菜单弹出速度略有提升。
2. 我使用双屏幕显示器，主屏幕上，右键单击菜单内容正常显示，但扩展屏幕无内容，与我此前反馈相同。
![2023-03-06 17 02 04](https://user-images.githubusercontent.com/123850195/223067395-bb848f14-d07a-4d06-9e3f-98b2bffa41c7.png)
![2023-03-06 17 02 28](https://user-images.githubusercontent.com/123850195/223067428-751e1893-bdcb-477e-add0-29114931286d.png)
3.建议：
喜欢当桌面为深蓝色壁纸时的亚克力效果
![2023-03-06 17 04 42](https://user-images.githubusercontent.com/123850195/223067650-c203153a-f92b-4ad6-8105-a1eadd90a5f4.png)
可否将这种效果应用到其他窗口的邮件效果上，这个灰色的不喜欢。
![2023-03-06 17 05 24](https://user-images.githubusercontent.com/123850195/223067932-afddbe61-3275-436d-aeb1-5499bf92f1f3.png)

**Comment by ALTaleX531** [comment]
[TranslucentFlyouts-Remake.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/10950396/TranslucentFlyouts-Remake.zip)
修复了没有内容的BUG

**Comment by ALTaleX531** [comment]
同时优化了动画流畅性
增加了适用于Windows11的主题边框着色

**Comment by ALTaleX531** [comment]
![image](https://user-images.githubusercontent.com/105535231/224535078-859f2efc-867a-4752-ac19-79c54ac93759.png)

在注册表 计算机\HKEY_CURRENT_USER\Software\TranslucentFlyouts 里新建DWORD32如图的相关值，重启TranslucentFlyouts可以应用相关设置，旧版也读取这里的设置，所以建议先删除旧的配置信息，可以通过旧版GUI的恢复默认设置进行

**Comment by shamodeyu** [comment]
1. 似乎是透明的菜单栏背景，尝试壁纸是灰色时，才看得清。
2. 输入q不退出程序

**Comment by ALTaleX531** [comment]
我现在才发现发的版本不是最新的😂，你可能得等一等，这个发出来的读不了配置且不透明度为0，但不是全透明，是Aero。至于退出不了程序，似乎不是我这边的问题。如果可以的话，可以给我一些关于动画的建议

**Comment by shamodeyu** [comment]
1. 对于动画，我没有特别的需求。如果提供了菜单弹出动画，建议可以调整时长。
2. 之前你发的注册表的贴图，因为我已经卸载之前的版本，remake版本是直接解压缩使用的，没有在注册表里搜索到相关内容。
3. 你的remake版本只发在这个issue下，其他人看得到吗？是不是要新开一个remake版本测试的issue，收集更多用户的反馈？

**Comment by ALTaleX531** [comment]
1、动画时长由AnimationDuration控制，以毫秒为单位，但发的那个版本有bug，无法读取配置。
2、主注册表项其实会在运行后自动创建
3、在UI写出来及相关功能逐渐成熟后，我会发布pre-release

**Comment by ALTaleX531** [comment]
#22 新版本在此测试 :)
