### ISSUE TITLE
xyplorer integration

### ISSUE THREAD

**Issue by spartaque12** [ALTaleX531/TranslucentFlyouts#23]
so im using win 11 22h2 and with custom explorer manager (xyplorer), seems like it does not work:
is there any way to make it compatible?
![XYplorer_2023-05-28_01-08](https://github.com/ALTaleX531/TranslucentFlyouts/assets/6484816/0fd7c699-5a19-4809-8a29-3c01772ff3b7)

**Comment by ALTaleX531** [comment]
The [new version](https://github.com/ALTaleX531/TranslucentFlyouts/releases/tag/v2.0.0-alpha) has been released

**Comment by ALTaleX531** [comment]
You can reopen this if you still encounter this issue.
