### ISSUE TITLE
Registry bug / Flyout bug

### ISSUE THREAD

**Issue by AndiDink00x** [ALTaleX531/TranslucentFlyouts#32]
1. There is a bug that sometimes when finish installation the registry folder/keys [ HKEY_CURRENT_USER\SOFTWARE\TranslucentFlyouts\ ] have not been imported

2. Also there is a bug on flyouts backdrop which is like this and cant change it ( text is purple because i am using custom theme )

![Screenshot 2023-08-01 162047](https://github.com/ALTaleX531/TranslucentFlyouts/assets/80290008/e6a936fb-baf3-42aa-b22c-4b90d22b1129)

**Comment by AndiDink00x** [comment]
**For 2.**
i found the problem, it seems that my custom.msstyles creates this issue, i tested another custom theme that of Rectified11 which supports also mica and it works perfectly. 
Now i should have find and tweak the theme properties but i have no clue... also i have to say that my custom theme also renders the every effect a little bit lighter as it should be , for example by using ExplorerBlurMica or MicaforEveryone that light tone in backround effects is still present no matter what type of effect im using

**Comment by ALTaleX531** [comment]
For 1.
You should manully create these registry folder/keys if they are not exist.
For 2.
I don't actually understand what bug the flyout has from your image, is the color mode not match? Backdrop type cannot be changed?

**Comment by AndiDink00x** [comment]
Wait you mean that its normal for flyouts to be rendered like in my pic ? If you use different effect, it changes just a little bit visually but pretty much the same.
Im just using Effect: 4 - Dark opacity: 1

Here im gonna post flyout example using Rectify's mica theme:
![Screenshot 2023-08-04 202241](https://github.com/ALTaleX531/TranslucentFlyouts/assets/80290008/ca93a592-0eef-4e81-8f05-066ea19dc54a)

Here my windows's dark theme: 
![Screenshot 2023-08-04 202129](https://github.com/ALTaleX531/TranslucentFlyouts/assets/80290008/6b24e583-86af-43a7-a909-b8f0157351e5)

Here are the themes to see yourself whats going on

[Niivu Android Paranoid 22H2.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12263266/Niivu.Android.Paranoid.22H2.zip)
[Rectify Mica theme.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12263270/Rectify.Mica.theme.zip)

**Comment by ALTaleX531** [comment]
I just installed [Niivu Android Paranoid 22H2.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12263266/Niivu.Android.Paranoid.22H2.zip) and tweaked according to your settings.
1.Before tweaking
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/bf7ecd0c-e1b7-44b9-875d-8eb1911a084b)
2.Tweaked
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/9dd60357-b347-4639-99a6-dddfda8c8642)
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/9c286fc9-70d2-4376-a4c3-d6cfd16c5e82)
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/34b3095a-c16d-4fb8-9da7-325f24d86925)

It looks fine.

**Comment by AndiDink00x** [comment]
> I just installed [Niivu Android Paranoid 22H2.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12263266/Niivu.Android.Paranoid.22H2.zip) and tweaked according to your settings. 1.Before tweaking ![image](https://user-images.githubusercontent.com/105535231/258521121-bf7ecd0c-e1b7-44b9-875d-8eb1911a084b.png) 2.Tweaked ![image](https://user-images.githubusercontent.com/105535231/258521205-9dd60357-b347-4639-99a6-dddfda8c8642.png) ![image](https://user-images.githubusercontent.com/105535231/258521225-9c286fc9-70d2-4376-a4c3-d6cfd16c5e82.png) ![image](https://user-images.githubusercontent.com/105535231/258521243-34b3095a-c16d-4fb8-9da7-325f24d86925.png)
> 
> It looks fine.

Context menus are OK but system tray flyouts-menus is the problem

**Comment by ALTaleX531** [comment]
> @ALTaleX531上下文菜单没问题，但系统托盘弹出菜单是问题

![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/38f6776d-ac04-4f80-af28-7013585350cb)
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/98d46737-6885-4534-b6e7-353cc6222c13)

**Comment by AndiDink00x** [comment]
Weird, it seems it only happens on my system but cant figure out what creates this bug.

**Comment by AndiDink00x** [comment]
issue gets closed
