### ISSUE TITLE
Popup menu render improperly with notepad++ shell extension

### ISSUE THREAD

**Issue by Luke-Marchant** [ALTaleX531/TranslucentFlyouts#34]
Hello, whenever I right click on a file on the desktop or from an Explorer window, the list of items in the flyout is incorrect. When I hover over options, they update to the correct list. I've attached a video to show what I mean. I'm using Win11 22H2, and v2.0.0-alpha.3 of TranslucentFlyouts.

https://github.com/ALTaleX531/TranslucentFlyouts/assets/67615785/9ce1948a-b8bd-40bf-aabc-5ee2979a3735

Also, I've attached the registry settings I use. From what I can tell, the issue occurs regardless of which settings I use.
[trfl_settings.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/12271786/trfl_settings.txt)

**Comment by ALTaleX531** [comment]
Have you installed any other third-party softwares, like StartAllBack?

**Comment by Luke-Marchant** [comment]
I have:
- MicaForEveryone
- ModernFlyouts (does not change the right-click flyouts like this software does, ModernFlyouts adds a music widget basically)
I've tried disabling both of these but it didn't fix my issue.

**Comment by ALTaleX531** [comment]
[TranslucentFlyoutsV2.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12272749/TranslucentFlyoutsV2.zip)
Please try this build, maybe it can solve this issue...

**Comment by Luke-Marchant** [comment]
Sorry, that didn't fix it :(

**Comment by ALTaleX531** [comment]
That's weird, I can't reproduce this bug on windows 10 and windows 11 in my test.🤔

**Comment by Luke-Marchant** [comment]
Is there any other info that might help?

**Comment by ALTaleX531** [comment]
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/906e7140-af3b-48fd-bcdb-428c38e73f7f)
Please use AutoRuns and check the items in "explorer" tab, I suspect that this issue was caused by some third-party shell extensions...

**Comment by ALTaleX531** [comment]
Please try this build
[TranslucentFlyoutsV2.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12297567/TranslucentFlyoutsV2.zip)

**Comment by Cris--** [comment]
@Luke-Marchant  little offtopic but plz share the Win11 wallpaper to me which u used in the video.
I tried reverse picture search but didn't find this in this color.

**Comment by Luke-Marchant** [comment]
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/67615785/025d09ee-2097-42f4-918d-3883275b6812)
@ALTaleX531 does anything look out of place? If not, I guess I'll try disabling them to see which one might be causing the issue
And @Cris-- [here ](https://cdn.discordapp.com/attachments/831536734692179978/1138941273588367410/thang.png)you go! It's just an edit of the default wallpaper

**Comment by Luke-Marchant** [comment]
Well, as it turns out, removing Notepad++'s shell integration fixed this. Weird, because it didn't show in AutoRun's list, and wasn't even under the normal `ShellEx\ContextMenuHandlers` registry key! Had to find the dll and unregister it manually.

**Comment by ALTaleX531** [comment]
@Luke-Marchant  Have you tried the latest release? I think it can solve this issue without remove Notepad++'s shell integration.

**Comment by sysven32** [comment]
@ALTaleX531 I'm using v2.0.0-alpha-4.1 and the Explorer popup menu is still bugged, when EnableFluentAnimation is on.

https://github.com/ALTaleX531/TranslucentFlyouts/assets/63135654/9022ec0b-622f-42a0-b870-d25f1f8816ba

**Comment by ALTaleX531** [comment]
@sysven32 Please try this build!
[TranslucentFlyoutsV2.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12317935/TranslucentFlyoutsV2.zip)

**Comment by sysven32** [comment]
@ALTaleX531 Thanks, the popup menu renders correctly now. 👍
