### ISSUE TITLE
Flyout animation bug

### ISSUE THREAD

**Issue by WiseTomCat** [ALTaleX531/TranslucentFlyouts#35]
As I was not able to replicate this bug to show you in the previous update which was fixed after a restart, with this update it is back again after enabling EnableFluentAnimation. I restarted and reinstalled but it hasn't worked on my windows 11 22h1 with mods like explorer patcher, uxtheme and ultrauxthemepatcher. The animation is now much smoother but unusable right now.

https://github.com/ALTaleX531/TranslucentFlyouts/assets/100816109/76aa562b-ff68-437a-8434-3ff53e1a60f3

**Comment by ALTaleX531** [comment]
Do you mean that unsettling white border? If yes, then unfortunately it will always be there unless "NoBorderColor" is specified, the reason why beta version flashed was it did not have this border, so it cannot be fixed right now...

**Comment by WiseTomCat** [comment]
@ALTaleX531  Thank you....it works with NoBorderColor but I guess I am not used to this new windows 11 fluent animation that it makes me feel a bit nauseous when I see it animating....so I will use this by turning animation off. I look forward to more updates on this brilliant aesthetic UI feature.
