### ISSUE TITLE
Cannot render popup menu scroll arrows properly

### ISSUE THREAD

**Issue by H5820121** [ALTaleX531/TranslucentFlyouts#36]
Thanks for the great app!
<img width="296" alt="image" src="https://github.com/ALTaleX531/TranslucentFlyouts/assets/105562828/8cfba40c-0bc3-4a58-a846-2b1f4ff308f0">

2.
>Downloading symbol files from Microsoft server is required at the first time

Where exactly do I need to download it, and what exactly do I need to do with it?
3. How can I choose Acrylic?
Thanks!

**Comment by AndiDink00x** [comment]
2. Make sure that a cmd window will popup telling that successfully downloads symbols when resigning in acc after install

3. There is a config page just read the repo page and you will find it

 https://github.com/ALTaleX531/TranslucentFlyouts/blob/master/CONFIG.md

**Comment by H5820121** [comment]
Thanks for the response!
1. What with the bug I reported, in dark mode, on the white lines above and below, which are in place of the menu scroll arrows?
>Make sure that a cmd window will popup telling that successfully downloads symbols when resigning in acc after install

I "Run "install.bat" as administrator" and I just got a message to logo off, what do you mean "resigning in acc after install". Can you please explain more, what exactly do I need to do?

3. I opened the link you gave, and this is what I got:
<img width="911" alt="image" src="https://github.com/ALTaleX531/TranslucentFlyouts/assets/105562828/e661309c-55ce-4c39-be38-46ce82b34e3c">

**Comment by AndiDink00x** [comment]
@H5820121 ALTaleX updated the repo just translate this for now https://github.com/ALTaleX531/TranslucentFlyouts/blob/master/Config/zh-cn/CONFIG.md

**Comment by H5820121** [comment]
Thanks for the response!
1. I did "Run "install.bat" as administrator" in the new var. and now it popup telling that successfully downloads symbols, but **I didn't see any entries created in the registry** HKEY_CURRENT_USER\SOFTWARE\TranslucentFlyouts\
Do I have to create the key "HKEY_CURRENT_USER\SOFTWARE\TranslucentFlyouts\" myself?
2. How are the changes there applied, do I need to log off?

**Comment by AndiDink00x** [comment]
@H5820121 1. yes, 2. no

**Comment by ALTaleX531** [comment]
I think you didn't set HKEY_CURRENT_USER\SOFTWARE\TranslucentFlyouts\Menu\EnableFluentAnimation to 1

**Comment by H5820121** [comment]
You were right, now it works!
Is it possible to make some kind of setting in the registry, so that there are no white lines in the popup, as you can see in the screenshot I brought above at the beginning of the issue?

**Comment by ALTaleX531** [comment]
Please try this build
[TranslucentFlyoutsV2.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12297567/TranslucentFlyoutsV2.zip)

**Comment by H5820121** [comment]
It's fine now, thanks!
