### ISSUE TITLE
注册表空白

### ISSUE THREAD

**Issue by shamodeyu** [ALTaleX531/TranslucentFlyouts#37]
已安装最新的v2 alpha 4，但注册中仍然是空白的。
![2023-08-08 14 42 29](https://github.com/ALTaleX531/TranslucentFlyouts/assets/123850195/d20b4b7d-a831-4b80-8d62-1a352ab29f2d)
可否单独提供一个注册表文件，双击可将注册表信息都加上？
我不太懂手动添加所有的注册表项。
谢谢！

**Comment by Undisputed00x** [comment]
[TranslucentReg.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12302572/TranslucentReg.zip)

**Comment by shamodeyu** [comment]
Thanks! I will try it.

**Comment by shamodeyu** [comment]
导入该注册表后，原来我在https://github.com/ALTaleX531/TranslucentFlyouts/issues/38最后贴的图里没有白色边框的，现在又有了。

**Comment by ALTaleX531** [comment]
因为导入注册表会覆盖已经创建的值，再次导入https://github.com/ALTaleX531/TranslucentFlyouts/issues/38 的reg就行，这也是我为什么犹豫要不要让你直接导入，
