### ISSUE TITLE
How to remove white border of popup menu in Windows 10

### ISSUE THREAD

**Issue by shamodeyu** [ALTaleX531/TranslucentFlyouts#38]
V2 alpha 4版本，右键菜单有白色边框，正常吗？如何去除白色边框？
![2023-08-08 14 51 25](https://github.com/ALTaleX531/TranslucentFlyouts/assets/123850195/8b49d105-36e9-4456-b092-b592e58e0126)

**Comment by ALTaleX531** [comment]
[preset.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/12290247/preset.txt)
把后缀名改成.reg导入到注册表，这不是bug

**Comment by shamodeyu** [comment]
白边又突然消失了。
好像调整过系统设置中的主题和颜色。
![2023-08-09 09 50 16](https://github.com/ALTaleX531/TranslucentFlyouts/assets/123850195/c366bff7-fb8f-4978-8ce2-965fa4816c12)
