### ISSUE TITLE
FluentAnimation or CustomRendering cause app crash since v2.0.0-bet.1

### ISSUE THREAD

**Issue by Undisputed00x** [ALTaleX531/TranslucentFlyouts#40]
After v2.0.0 beta1 when i enable FluentAnimation or CustomRendering, and click on registry (except the option key itself) its just shutdown, also happens on ExplorerPatcher
video:
https://imgur.com/a/TQFYOLy

better quality:
https://pixeldrain.com/u/XNZfW4fy

**Comment by ALTaleX531** [comment]
I see, it cause the app crash.

**Comment by Undisputed00x** [comment]
@ALTaleX531 Well it fixed the crashes when clicking on Registry but it still conflicts with ExplorerPatcher (although this is not that of a big issue for me)

**Comment by ALTaleX531** [comment]
Weird, ExplorerPatcher won't crash in my test. But I think it was a OS issue because `d3d11!D3D11CreateDevice` cause a access violation internally in the former release and I can't reproduce it in Windows 10.

**Comment by Undisputed00x** [comment]
@ALTaleX531 You mean that you can open  dropdown menus in ExplorerPatcher e.g changing the taskbar ?

**Comment by ALTaleX531** [comment]
Of course.
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/068bad49-56e3-4468-88f3-fbde55010707)

**Comment by Undisputed00x** [comment]
@ALTaleX531 Ok then you should be right, so i guess issue got fixed
