### ISSUE TITLE
Installation succeeds but it doesn't work (Win 11) - does this rely on inbuilt Transparency Effects?

### ISSUE THREAD

**Issue by e-t-l** [ALTaleX531/TranslucentFlyouts#44]
Does this project utilize the same "Transparency effects" that are in `Windows Settings > Personalization > Colors`? Because if that's the case, then that is probably why this isn't working on my system; I've had issues with getting Windows Transparency Effects to work (see this thread if you're curious about the specific issue: https://forums.tomshardware.com/threads/3813385)

However, I also noticed that even after unzipping v2.0.0-alpha.4, running install.bat and signing out of my user profile (and when I signed back in, I _did_ see a console window talking about downloading symbols that I believe is related to TranslucentFlyouts)... there were NO REGISTRY KEY for TranslucentFlyouts. And obviously, no translucency effects were working. I tried creating the registry entries described in [config.md](https://github.com/ALTaleX531/TranslucentFlyouts/blob/6168e09e34ca3229247943ea7ecc9d54a147dfe5/CONFIG.md) manually and setting appropriate values, but it still didn't work.

**Comment by ALTaleX531** [comment]
Yes, "Transparency effects" is required to be enabled in Windows 11.  Please try to delete `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm\ForceEffectMode` and restart dwm.exe.

**Comment by e-t-l** [comment]
Deleting `ForceEffectMode` key solved it! Didn't even need to restart DWM.
