### ISSUE TITLE
EnableCustomRendering crashes Registry Editor

### ISSUE THREAD

**Issue by e-t-l** [ALTaleX531/TranslucentFlyouts#46]
When `Computer\HKEY_CURRENT_USER\Software\TranslucentFlyouts\Menu\EnableCustomRendering` = `1`, right-clicking anywhere in Registry Editor causes the application to hang and then crash.

--
v2.0.0-alpha.4
Windows 11 Home version 22000

**Comment by ALTaleX531** [comment]
Duplicate of #40
