### ISSUE TITLE
How to install a new version when an old one is already installed?

### ISSUE THREAD

**Issue by H5820121** [ALTaleX531/TranslucentFlyouts#47]
This application is amazing!

To install a new version, do I first must to uninstall the previous version and then to logoff and only then to install the new version and logoff again for the new version?

**Comment by ALTaleX531** [comment]
Currently there two ways.
1. Uninstall the previous version, logoff and then install the new version.
2. Install the new version directly at a new location which is different to the previous one, and then logoff.

**Comment by H5820121** [comment]
Thanks for the response!

**Comment by WiseTomCat** [comment]
@ALTaleX531 I think I found a faster way....move the files from the current folders to the desktop since we cannot delete this (this will stop some apps from working). Then copy the new files to the folder...press install and log off. and delete the old files in desktop after logon. This process will require only one logoff.

**Comment by H5820121** [comment]
@WiseTomCat 
>move the files from the current folders 

I don't understand what you mean, can you please explain what exactly to do step by step?

**Comment by ALTaleX531** [comment]
Well, It seems too complex for users to update. I plan to bring a few optimizations that logoff is no longer needed...

**Comment by H5820121** [comment]
Thanks, that would be great!

**Comment by WiseTomCat** [comment]
@H5820121 I have been using this method to update TF.....while the older TF is currently active the files cannot be deleted but they can be moved so.....I moved the files from the older TF to desktop except for the Symbols folder.....and then copy the new files to the same location (in my case it is C:\Program FIles\TranslucentFlyouts). Then press the install.bat(I dont think this step is required)....and then finally log off and logon.

**Comment by H5820121** [comment]
@WiseTomCat 
> can be moved 

I can't move them to another location as they are locked by other processes.

**Comment by WiseTomCat** [comment]
@H5820121 thats strange....didnt figure it would be different in other machines....I have been doing it for the last 3 updates. Have you enabled many registry settings..like EnableCustomRendering? also I'm still on windows 11 21H2. Hopefully soon TF will get to a point where we will know it has been fully integrated into the system through an app.
