### ISSUE TITLE
Improving popup menus design

### ISSUE THREAD

**Issue by krlvm** [ALTaleX531/TranslucentFlyouts#5]
Hello,

Thank you for publishing this work. I've forked it and made some improvements, making it more in line with Windows design.
I had to drop quite a lot of functionality to focus on popup menus, so before submitting a patch, I'm asking for your opinion on this - does this fit your view of the development of the project, or do I need to maintain a separate fork?

Removed functionality:
- Customizability
- I had to drop Windows Runtime related code and temporary drop tooltips support
- With no more customization options left, I removed the user interface and tray icon
- I have limited the scope to File Explorer by default to avoid breaking some applications in unexpected ways, e.g. it is affects the appearance of desktop icons text

Improvements:
- Instead of reducing background color opacity, I've found a way to detect the color and I'm passing it to `SetWindowCompositionAttribute` as tint value with hardcoded opacity. On Windows 11, `0x2` flag is needed to increase luminosity.
- I implemented dark mode detection and hooked up a handler to render the separators and hover state of the popup item, and after a long search for the right values, I hardcoded the opacity and color values for them, which forced me to remove all the functionality related to customizability.
- Good looking borders on Windows 11 with `DwmSetWindowAttribute` call on `DWMWA_BORDER_COLOR` and removed white border on Windows 10 by drawing on non-client area after some delay.
- Fixed an issue where after selecting the option, the fade out animation is black because in that case Windows ignores the alpha channel. After monitoring StartAllBack calls, I've noticed that it disables the animation temporary with `SystemParametersInfoW` on `SPI_SETSELECTIONFADE` and draws its own popup window which resembles the animation. I've managed to did the same, but instead of manually drawing the text on this window, I capture this part of the actual popup menu with `BitBlt`.
- Some other minor quality of life improvements and bugfixes which hit customizability even more.

None of this can be done without hardcoding and narrowing the scope for customization, so I'm interested in your opinion on this.

https://user-images.githubusercontent.com/51774833/181915733-00d5d606-a5f3-40b1-927a-8a16b498add8.mp4

https://user-images.githubusercontent.com/51774833/181915736-9670e0ae-908f-4ba2-a3f6-89c1cad3149a.mp4

**Comment by ALTaleX531** [comment]
@krlvm Hello, thank you for your contribution to this project. Since the release of TranslucentFlyouts, we have mainly focused on customizability, functionality, and tried to avoid hardcoded implementations. I personally think that you can apply these changes to your project AcrylicMenus, these changes have specialized support for popup menus, and AcrylicMenus will bring a better experience to users and will not be deprecated because of this. Besides, we would appreciate it if you could add our names to the list of contributors for consideration. Best wishes, ALTaleX531.

**Comment by ALTaleX531** [comment]
If you have any other questions, you can ask @Maplespe

**Comment by krlvm** [comment]
Thank you for feedback, I've published the modified source code into [AcrylicMenus](https://github.com/krlvm/AcrylicMenus) repository with attribution - this would not have been possible without your project..

Let me know if I can help you by porting some improvements which does not damage customizability.

**Comment by Maplespe** [comment]
Of course, if we can, we want to keep the customization options and user interface.
