### ISSUE TITLE
右键弹出菜单中有些有白色背景

### ISSUE THREAD

**Issue by shamodeyu** [ALTaleX531/TranslucentFlyouts#51]
红色框内的图标有白色背景，但下一级菜单的图标没有（红色箭头所指）。
![2023-08-18 08 30 43](https://github.com/ALTaleX531/TranslucentFlyouts/assets/123850195/8a262b15-7680-41aa-8096-2cf7ff9c5bd9)

建议去掉白色背景。

**Comment by ALTaleX531** [comment]
老实说这不是我的问题，因为这些软件的开发者提供的图标自身就带了一层白底，不过我还是可以考虑追加一个扣除背景的选项的

**Comment by ALTaleX531** [comment]
最新版已提供该功能，请按照配置文件的说明操作
