### ISSUE TITLE
在下拉菜单之间快速切换时会引发应用崩溃

### ISSUE THREAD

**Issue by LOGYT-Eberk** [ALTaleX531/TranslucentFlyouts#52]
在下拉菜单之间快速切换时会引发应用崩溃，无论是系统应用还是第三方应用，百分百复现。
系统注册表编辑器：
![1](https://github.com/ALTaleX531/TranslucentFlyouts/assets/117907349/5cc1719f-eb9c-470e-8c38-0c79b4df23a2)
第三方应用Bandizip：
![2](https://github.com/ALTaleX531/TranslucentFlyouts/assets/117907349/3f7c76c1-e41d-400f-9ed5-1f1c7a72cf8d)

**Comment by ALTaleX531** [comment]
昨天发布的beta.2已经修复了这个问题，如果那个版本还有问题再跟我讲一声

**Comment by LOGYT-Eberk** [comment]
感谢，问题已经解决了，之前出问题的版本是v2.0.0-alpha.4.2
