### ISSUE TITLE
Notification when a new version is released

### ISSUE THREAD

**Issue by H5820121** [ALTaleX531/TranslucentFlyouts#53]
Is it possible to give you an email, where you will notify me when a new version is released, I am sure that many more users will be happy about this option.
Many thanks!

**Comment by ALTaleX531** [comment]
Actually, you can achieve this by using github built-in functionality called `Watch` which will automatically send emails to you.
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/1df476bc-41ae-4aed-87ce-76e6f4fcf7ad)

**Comment by H5820121** [comment]
Thanks for the response!
Which option should I choose there, so that there is a notification only about a new version, and not about new issues?

By the way, I installed the new version and did not see any change regarding the IDM menu.
Maybe something went wrong with the installation, how can I check which version was installed?

**Comment by ALTaleX531** [comment]
You can just tick `Releases` in the option `Custom` as the image below.
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/065d3bb8-d778-4c75-8854-31e650c4e225)

For IDM, you should also install x86 version which is intended for 32-bit application.
