### ISSUE TITLE
Can this be extended to the taskbar?

### ISSUE THREAD

**Issue by e-t-l** [ALTaleX531/TranslucentFlyouts#54]
I have no idea how this program works on the back end, so forgive me if this is a dumb question. Is it possible to make it apply to the Windows taskbar as well? (so it could be used as an alternative to [TransparentTaskbar](https://github.com/TranslucentTB/TranslucentTB/), for example?)

**Comment by ALTaleX531** [comment]
No. If you also want to make taskbar translucent, why not just pair it up with [TranslucentTB](https://github.com/TranslucentTB/TranslucentTB)?

**Comment by e-t-l** [comment]
> If you also want to make taskbar translucent, why not just pair it up with TranslucentTB?

I do! I was just curious whether they could be combined, since running 1 program is better than 2. Thank you for your answer.
