### ISSUE TITLE
弹窗Rundll32.exe设备不识别此命令，软件无法自动启动

### ISSUE THREAD

**Issue by shamodeyu** [ALTaleX531/TranslucentFlyouts#56]
Windows 10 Build 2004（64位）安装了TranslucentFlyouts 2.0 beta 2，但每次开机后都出现以下弹窗，软件无法启动。
![2023-08-23 23 25 05](https://github.com/ALTaleX531/TranslucentFlyouts/assets/123850195/95aca453-6bd1-4472-a2a4-0ec0cae51694)

双击debug.bat，软件可以启动。

**Comment by ALTaleX531** [comment]
如果最新版仍有此问题，你可以重新打开这个issue

**Comment by e-t-l** [comment]
@ALTaleX531 I am encountering this exact same issue with the latest version, v2.1.0...

**Comment by ALTaleX531** [comment]
> @ALTaleX531 I am encountering this exact same issue with the latest version, v2.1.0...

I think you have to reinstall it.

**Comment by e-t-l** [comment]
Sorry, I should have given more information. I get this error when I run install.bat.

**Comment by ALTaleX531** [comment]
Please show me a screenshot, I think your issue is different.

**Comment by e-t-l** [comment]
> Please show me a screenshot, I think your issue is different.

@ALTaleX531 I created a new issue for it, #60
