### ISSUE TITLE
Uninstall/Stop error

### ISSUE THREAD

**Issue by Bo-sudo** [ALTaleX531/TranslucentFlyouts#59]
Just got TranslucentFlyouts today, and since it was all batch files, I tested the uninstall, the stop service and the debug. The uninstall and stop didn't work for me.

Debug: Seemingly nothing happens.

Uninstall: I get this error saying "The system could not find the file specified."
![Screenshot 2023-08-27 193718](https://github.com/ALTaleX531/TranslucentFlyouts/assets/77079248/d4a23ed5-e783-4999-9434-98c070bf9b30)

Stop: I get this error that says "The service has not been started."
![Screenshot 2023-08-27 193742](https://github.com/ALTaleX531/TranslucentFlyouts/assets/77079248/5454392b-d93d-470f-af10-2f4b73c0461f)

**Comment by ALTaleX531** [comment]
I don't think it's a bug because you haven't even run `install.bat` as an administrator.

**Comment by Bo-sudo** [comment]
Oh okay.
