### ISSUE TITLE
Install error "Rundll32.exe: Access is denied."

### ISSUE THREAD

**Issue by e-t-l** [ALTaleX531/TranslucentFlyouts#60]
When I run install.bat for the latest build, v2.1.0, I get the error "Access is denied" from Rundll32.exe. It doesn't matter if I run it as administrator or not. As you can see from the screenshot below, it looks like TransparentFlyouts is also failing to download symbols. I was using (and indeed, I still am using) v2.0.0-alpha-4.2 x64, since it and all previous versions installed without problem.

I commented on issue #56 thinking it was related, but it's possible I was mistranslating. I also have no idea if this is related to #41.

I'm running Windows 11 Home v22621.1413.

![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/40775958/76b529af-5e36-4c65-a025-b55e1b744381)

**Comment by ALTaleX531** [comment]
Did you really run these batch files as administrator? This error could only be seen when it has not enough privileges or blocked by anti-virus software.

**Comment by e-t-l** [comment]
> Did you really run these batch files as administrator? 

Yes. 

> or blocked by anti-virus software

Likely, but I had whitelisted the .bat in my antivirus already. Are there any other files/folders in I need to whitelist?

**Comment by ALTaleX531** [comment]
I suggest temporarily disabling anti-virus software, then run these batch files again.

**Comment by e-t-l** [comment]
Restarted PC, disabled all AV, ran bat as admin, success. Thanks for your help.
