### ISSUE TITLE
[crash but not TF] TranslucentFlyouts menus make interesting interaction with some program/application

### ISSUE THREAD

**Issue by MuscularPuky** [ALTaleX531/TranslucentFlyouts#61]
I think it overloads program/application and leaks memory of explorer. I thought explorer or TF would crash but completly opposite.

funny. I like ths crash :)

fluent animation is sus. V1 was fine. CAn I get blacklist or exclusion list? Some program/applications have compatibility issue

https://github.com/ALTaleX531/TranslucentFlyouts/assets/93962018/639863d7-b99b-4a16-83b7-c5d29d167f80

![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/93962018/f154c543-118c-4ce9-88d3-88721e689aa0)

**Comment by ALTaleX531** [comment]
The new version has fixed this issue and added the functionality of exclusion list.
