### ISSUE TITLE
Support for round corner on Win10

### ISSUE THREAD

**Issue by Satanarious** [ALTaleX531/TranslucentFlyouts#62]
Support for round corners on windows 10 with customizable border radius.
Is this possible?

**Comment by ALTaleX531** [comment]
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/da5c255d-7fd6-4fa7-a477-ec8cf65d229a)
The backdrop is always not round.

**Comment by Satanarious** [comment]
Yeah, that's a problem I've faced in the past.
Closing this as `wont-fix`.

**Comment by ALTaleX531** [comment]
However, `UpdateLayeredWindow` can let backdrop round but it has relavant side-effect about layered window.

**Comment by Satanarious** [comment]
On Second thought, Can we render a transparent((Invisible)) background and, inside that a layered window with round corners?

**Comment by ALTaleX531** [comment]
Then, the drop shadow effect will be clipped and it will also affect fluent menu animation.

**Comment by Satanarious** [comment]
Yeah, I forgot about the animations. My bad.
