### ISSUE TITLE
Some context menus are unreadable when using a custom dark theme

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [ALTaleX531/TranslucentFlyouts#63]
So i'm using [Niivu's macOS dark theme](https://www.deviantart.com/niivu/art/macOS-for-Windows-11-22H2-952231551) and with it some context menus brake and have white text on white background.
![Skärmbild 2023-09-09 093212](https://github.com/ALTaleX531/TranslucentFlyouts/assets/74187631/1525cb09-a0be-402c-9b5d-eecd855becdb)
![Skärmbild 2023-09-09 092800](https://github.com/ALTaleX531/TranslucentFlyouts/assets/74187631/c696fcdd-76f0-4a5d-ba95-1e332d07d876)

**Comment by ALTaleX531** [comment]
This third-party theme forces the light mode theme part to be dark, so here comes the issue.
You can set dword value `HKEY_CURRENT_USER\Software\TranslucentFlyouts\Menu\LightMode_GradientColor` to `0x412B2B2B` to solve it, or import the `fix.reg` of [fix.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12565319/fix.zip).

**Comment by ALTaleX531** [comment]
Hi there, is your issue solved? I am going to close this issue since you didn't respond for a long time. If you still have some problems, it is OK to reopen it.

**Comment by IdkWhatToCallMe123** [comment]
oh sorry for not responding but my issue appears to be solved.

Thank you so much <3
