### ISSUE TITLE
新的配置文档缺少一些旧的参数

### ISSUE THREAD

**Issue by ococoaocoaco** [ALTaleX531/TranslucentFlyouts#64]
我指的是这个`[配置文档](https://github.com/ALTaleX531/TranslucentFlyouts/blob/master/Config/zh-cn/CONFIG.md)`
比如旧版本“Menu\Hot"内的CornerRadius值，旧版本的配置文档标注为“控制悬浮时的圆角半径大小”，换个形容方式就是鼠标位置的选项的圆角半径。
CornerRadius值，不、是整个\Hot项的参数在新版本的配置文档中都消失了，然而就我举例的这个圆角半径值，依然是可以使用的，如果我没有先前版本的记录，这个圆角半径就无从更改(因为永远不会知道还有这个参数)....

我的意思是，注册表位置的变化让人感到混乱，尤其对于想更新TranslucentFlyout版本的人。

提个很业余的意见，，能否多一个.ini文件的控制方法，这样应该会直观很多

**Comment by ALTaleX531** [comment]
这些注册表的配置信息其实一直都在，那么多个版本的迭代过程只删除了`NoSystemOutline`，对更新没什么影响
有一大部分有关于自定义渲染的重复配置信息其实都在这里[CustomRendering](https://github.com/ALTaleX531/TranslucentFlyouts/blob/master/Config/zh-cn/Menu/CustomRendering/CONFIG.md)，不过出于未知原因Hot的跳转链接烂了，之后我会修复它的
目前不打算加.ini的控制方法，因为现在已经有大佬开发出[GUI](https://github.com/Satanarious/TransparentFlyoutsConfig/releases/tag/v1.0.0-alpha.3)来了，已经足够的直观和方便了...
<img width="713" alt="image" src="https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/e7e4197d-543a-4c9e-943d-ec3701158098">

**Comment by ALTaleX531** [comment]
你好，你已经有较长一段时间没有回复了，请问是否还有其它问题需要反馈？如果没有的话，我将会不久后关闭这个issue

**Comment by ococoaocoaco** [comment]
> 你好，你已经有较长一段时间没有回复了，请问是否还有其它问题需要反馈？如果没有的话，我将会不久后关闭这个issue

抱歉，因为我只是个业余的家伙，之前我也不知道要回复什么hhh，当然也不知道Issue的规则
如果关闭问题是“Close with comment”，那我现在关闭吧，辛苦您关注了。

**Comment by ococoaocoaco** [comment]
> 你好，你已经有较长一段时间没有回复了，请问是否还有其它问题需要反馈？如果没有的话，我将会不久后关闭这个issue

大佬，我几天前想给win10虚拟机更新TranslucentFlyouts。
我先在旧版本目录用uninstall.bat卸载，然后删除相关文件
重启，在一个新的位置、运行新版本的Install.bat，弹出的CMD显示的字符都会变成“?????"
重启，CMD界面自动出现，一号虚拟机依然乱码，二号虚拟机在重启后显示就恢复正常
我个人觉得这个和虚拟机应该没什么关系......就是反馈一下

**Comment by ALTaleX531** [comment]
你的控制台代码页没设好或出于某种原因坏了，跟TranslucentFlyouts没关系，你可以自行搜索解决，或者简单粗暴的把系统语言调成英文来解决
