### ISSUE TITLE
Loading symbol files exception 

### ISSUE THREAD

**Issue by Cris--** [ALTaleX531/TranslucentFlyouts#66]
On Windows 22H2 Build 22621.2359. Wrong download path or must we wait?

```batchfile
[MenuHandler] Loading symbol files from local disk or Microsoft symbol servers, please make sure your network connection is alright...

[MenuHandler] An exception thrown while resolving symbol files, some features of TranslucentFlyouts will be limited or unavailable! (hresult: 0x80070002)

[MenuHandler] We tried to download appropriate symbols package from Microsoft server but it failed.
Without symbol files, some features of TranslucentFlyouts may be limited or unavailable, do you want to retry it now? (Y/N)
```

**Comment by ALTaleX531** [comment]
It seems that you don't have a valid Internet connection, press Y to retry again...

**Comment by Cris--** [comment]
nope, that was not the problem yesterday!

**Comment by ALTaleX531** [comment]
I mean TF cannot access http://msdl.microsoft.com/download/symbols which is the website of microsoft symbol server to download appropriate symbols. You can retry a few more times.

**Comment by Undisputed00x** [comment]
@Cris-- Also happened to me after sfc /scannow. For me it needed 2 or 3 reboots to download for both 32bit and 64bit.

**Comment by Cris--** [comment]
No luck yet after several reboots, whole system check (chkdsk, DISM, etc).
Maybe anyone can simply share the symbol folder to me for W64 22H2 Build 22621.2359 plz?

**Comment by Undisputed00x** [comment]
> No luck yet after several reboots, whole system check (chkdsk, sfc, DISM, etc). Maybe anyone can simply share the symbol folder to me for W64 22H2 Build 22621.2359 plz?

delete symbols in TF folder

**Comment by ALTaleX531** [comment]
@Cris-- Please upload your uxtheme.dll and shell32.dll to me (C:\Windows\System32), maybe I can download these symbols for you...

**Comment by Cris--** [comment]
> @Cris-- Please upload your uxtheme.dll and shell32.dll to me (C:\Windows\System32), maybe I can download these symbols for you...

Great: https://we.tl/t-K7uLiaAYop

**Comment by ALTaleX531** [comment]
> From the system32 folder. There are also on SysWOW64 but smaller. I think the bigger ones are for x64 and the right one, or?

Yes, you are right. 

But unfortunately I also encountered this issue, and it seems to be the problem of Microsoft. They haven't released the symbol file of this build (shell32.dll). Luckily, most of the functionalities of TF are all fine, except `NoModernAppBackgroundColor`.

I suggest waiting for a few more days or downgrading your system. Honestly, I don't know why Microsoft still hasn't released the symbol file.

**Comment by Cris--** [comment]
![Screenshot 2023-09-27 110100](https://github.com/ALTaleX531/TranslucentFlyouts/assets/7994691/69780ab8-9050-4dcc-bdbc-319eab04eac1)

Done!

**Comment by e-t-l** [comment]
> > From the system32 folder. There are also on SysWOW64 but smaller. I think the bigger ones are for x64 and the right one, or?
> 
> Yes, you are right.
> 
> But unfortunately I also encountered this issue, and it seems to be the problem of Microsoft. They haven't released the symbol file of this build (shell32.dll). Luckily, most of the functionalities of TF are all fine, except `NoModernAppBackgroundColor`.
> 
> I suggest waiting for a few more days or downgrading your system. Honestly, I don't know why Microsoft still hasn't released the symbol file.

I am encountering the same error message, so I suspect I have the same problem. How do you manually download the symbols file from Microsoft? Is there a website for it?

**Comment by 03302024** [comment]
> How do you manually download the symbols file from Microsoft? Is there a website for it?

Did you find a way for doing that? I am also facing issues and I wanted to try manual downloading and installation.
