### ISSUE TITLE
Crashing Valorant

### ISSUE THREAD

**Issue by Satanarious** [ALTaleX531/TranslucentFlyouts#68]
I have been trying to fix my [Valorant](https://playvalorant.com/) installation for 20 days. It used to crash on my new PC everytime. I uninstalled TFs, and voila! Everything ran perfectly. I was wondering if you could try to figure out the issue because it was not the case on the earlier builds.

**Comment by ALTaleX531** [comment]
I have a bad news for you, it looks like it's anti-cheat mechanism destroyed itself in the process of mistakenly forcing the unloading of third-party modules. Even if TF was modified to do nothing or disabled, it would still crash. Please report it to the officials if you can, as there's nothing I can do. The current solution is to temporarily stop TF before playing.
I apologize for TF bothering you to play Valorant, however there is nothing I can do about it at the moment...

**Comment by Satanarious** [comment]
I'll let the support team know. Thanks for the insight.

**Comment by Satanarious** [comment]
They closed my ticket, don't think I can inform them now. It's sad that I had to uninstall this because of it. I'll try to write a script to install or uninstall TFs when Valorant runs or exits, respectively through my game launcher.

**Comment by Satanarious** [comment]
I tested today and cannot run Valorant at all with TF installed and running.

**Comment by ALTaleX531** [comment]
This is a very strange problem, and it's probably because the anti-cheat algorithm is implemented differently on different systems. The system I'm testing on is Windows 11, which may have something to do with it.

**Comment by Satanarious** [comment]
I'm running Windows 10 v19045.4123. It's really unfortunate that I cannot use TF even though I'm working on it.
