### ISSUE TITLE
TranslucentFlyouts causes text to not render properly in Bulk Rename Utility

### ISSUE THREAD

**Issue by ice051128** [ALTaleX531/TranslucentFlyouts#7]
I'm not sure why this causes the text to not render properly in the menu and main window of another program, but turning off TranslucentFlyouts fixes the issue immediately. Please look into it

Example of issue:
![Screenshot_3](https://user-images.githubusercontent.com/49018832/204123549-c7dea326-5600-4a86-aa78-5e4b3d103118.png)

What it should look like:
https://www.bulkrenameutility.co.uk/assets/img-bru/bru_main2.png

**Comment by ALTaleX531** [comment]
We are working on it. 
However, it is difficult to guarantee that this problem can be fixed, as this is a closed-source third-party app
