### ISSUE TITLE
Crash on Drag and Drop When Tooltip Enabled

### ISSUE THREAD

**Issue by bbmaster123** [ALTaleX531/TranslucentFlyouts#70]
whenever I try to drag a file to another folder, explorer.exe crashes and restarts every time. When I disable tooltip using the configuration GUI, drag and drop will then work correctly. This happens on both my systems, one with windows 11 22621 and the other with latest windows 10 .

happy to provide logs when I get home. IIRC visual studio said something about a CLSID not being implemented and cannot be found.
cheers :)

**Comment by ALTaleX531** [comment]
Already fixed in the latest version.
