### ISSUE TITLE
version 2.1.0 doesn’t work in Windows 10, makes Explorer crash

### ISSUE THREAD

**Issue by lucaspestana** [ALTaleX531/TranslucentFlyouts#71]
Hello there!
**I am Windows 10 user, 22H2, just updated to build 19045.3570.**
Additional note: I also have StartIsBack installed, in case this is relevant (along with a handful of other UI/UX modifying utilities).

So, I have old version 1.0.5 installed on my machine (which includes "TranslucentFlyoutsGUI.exe" as well as "TranslucentFlyoutsLib.dll").

As soon as my OS was just updated by Windows Update, I noticed the right-click menu of Windows/File Explorer was a dull opaque dark grey (with 11-esque rounded borders -- I don't remember if these are a result of TranslucentFlyouts or not).

I proceeded to the TranslucentFlyouts homepage on GitHub to download the latest version… and was a little puzzled not to find any "TranslucentFlyoutsGUI.exe" file -- well, whatever.

.

**_Upon installing version 2.1.0, Explorer will either crash or temporarily show a seemingly empty right-click menu, where the menu options will only become visible as I hover the mouse cursor over them… and eventually crash at some point._**

_For now, I'm back to using old trusty 1.0.5 -- it no longer renders Explorer's right-click menus translucent, unfortunately, but it still manages to apply effects to the right-click menus of most other Win32* (* I guess‽) programs, such as Notepad; with some other apps, however, it just won't work either, but at least nothing will crash._

**Comment by ALTaleX531** [comment]
Fixed in the latest version.
