### ISSUE TITLE
After the installation and restart the computer, right-click the pop-up menu turns black | 在安装后重启电脑后右键弹出菜单变成黑色

### ISSUE THREAD

**Issue by iatri** [ALTaleX531/TranslucentFlyouts#72]
![屏幕截图-Program Manager_2023-10-27_00-30-57](https://github.com/ALTaleX531/TranslucentFlyouts/assets/141122842/b3b21ef8-30b9-4926-8a0b-28cbbac102c6)
![屏幕截图-Program Files_2023-10-27_00-32-45](https://github.com/ALTaleX531/TranslucentFlyouts/assets/141122842/8ca94fb8-2459-4957-95b6-c783a963e6a3)
如图，在运行install.bat后特效是正常的，但重启电脑之后右键菜单就会变为灰色，并且只有文件资源管理器的右键菜单的界面有这个问题，其他的应用没有出现问题
我已试过重新安装，使用其他的版本，使用其他设置与默认设置，也有这个问题
(As shown in the figure, the effects are normal after install.bat is run, but the right-click menu will turn gray after restarting the computer, and only the right-click menu interface of File Explorer has this problem, other applications do not have problems
I have tried reinstalling, using a different version, using other Settings with the default Settings, and also have this problem)
![屏幕截图-注册表编辑器_2023-10-27_00-31-34](https://github.com/ALTaleX531/TranslucentFlyouts/assets/141122842/707a3240-3896-45b1-8a11-ce8e89148a0e)
![屏幕截图-设置_2023-10-27_00-41-41](https://github.com/ALTaleX531/TranslucentFlyouts/assets/141122842/46f00452-1a67-4ac8-9413-a103da1c7351)
可以解决这个问题嘛？
(Can you solve this problem?)

**Comment by ALTaleX531** [comment]
出于某些问题TF没有正确识别出弹出菜单的颜色模式，从而使用适用于暗模式的背景效果，请问是否有在使用第三方主题或其它美化工具？

**Comment by iatri** [comment]
没有用第三方主题，有使用[TranslucentTB](https://github.com/TranslucentTB/TranslucentTB)和[MicaForEveryone](https://github.com/MicaForEveryone/MicaForEveryone)
我发现只在默认应用模式为深色是会出问题
![屏幕截图-Program Manager_2023-10-27_22-32-26](https://github.com/ALTaleX531/TranslucentFlyouts/assets/141122842/aab0d5bb-65ee-4817-9970-5f189d606df4)
![屏幕截图-Program Manager_2023-10-27_22-34-20](https://github.com/ALTaleX531/TranslucentFlyouts/assets/141122842/18209281-27ed-4d6c-82a9-ea369597e9c6)

**Comment by ALTaleX531** [comment]
请查看最新版本
