### ISSUE TITLE
When modern Fluent pop-up animation for menus is activated, the explorer crashes after each call of the context menu

### ISSUE THREAD

**Issue by Andrew-Sor** [ALTaleX531/TranslucentFlyouts#75]
I have Windows 10 version 22H2 and build 19045.3636. When I change the EnableFluentAnimation value in the registry to 1, the explorer crashes after each opening of the context menu. Without animation everything is fine. TranslucentFlyouts version 2.1.0.

**Comment by bbmaster123** [comment]
are you positive its the fluent animations? For me it was tooltips that was causing crashes when dragging and dropping files. Once I set that to disabled, animations worked fine on my windows 10 and windows 11 systems. 
btw, if you missed it, grab Satanarius's config GUI, saves you the trouble of going into the registry https://github.com/Satanarious/TransparentFlyoutsConfig/releases/tag/v1.0.0-beta.1

cheers

**Comment by Andrew-Sor** [comment]
> are you positive its the fluent animations? For me it was tooltips that was causing crashes when dragging and dropping files. Once I set that to disabled, animations worked fine on my windows 10 and windows 11 systems. btw, if you missed it, grab Satanarius's config GUI, saves you the trouble of going into the registry https://github.com/Satanarious/TransparentFlyoutsConfig/releases/tag/v1.0.0-beta.1
> 
> cheers

I don't quite understand what smooth animation means. And with hints and dragging everything is fine for me. And just in case, where can I turn this off so I can check? And I have the program from the repository you provided. And by the way, there is no difference if I configure it through it or the registry.

**Comment by bbmaster123** [comment]
> Is there any other animation there? 

No, I just meant are you sure having animations enabled was the issue. 


> And by the way, there is no difference if I configure it through it or the registry

Yes, I am aware, the GUI is just a little more convenient than manually editing the registry, most of the time 

Please see image below, this is the option I disabled to stop explorer from crashing:
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/92948468/49623b45-feba-4c5d-b72e-c6997ccc6d1b)


If you're positive its the animations causing the crashes, we might need to take into account what other programs or mods you have running, and whether or not windows is damaged. Have you tried running the dism and sfc commands?

**Comment by Andrew-Sor** [comment]
> > Is there any other animation there?
> 
> No, I just meant are you sure having animations enabled was the issue.

> 
> > And by the way, there is no difference if I configure it through it or the registry
> 
> Yes, I am aware, the GUI is just a little more convenient than manually editing the registry, most of the time
> 
> Please see image below, this is the option I disabled to stop explorer from crashing: ![image](https://user-images.githubusercontent.com/92948468/283520223-49623b45-feba-4c5d-b72e-c6997ccc6d1b.png)
This is "use global settings". And in my global settings I have “no”.
> 
> If you're positive its the animations causing the crashes, we might need to take into account what other programs or mods you have running, and whether or not windows is damaged. Have you tried running the dism and sfc commands?
I use quite a few programs...😅 Regarding damage... I once tried to install aero glass because someone on YouTube showed that thanks to it a blur effect appears in the window title bars. But when I installed it, explorer started crashing very often. And I hastened to remove this program. Since then it sometimes crashes for me... I haven’t tried running commands for a very long time...

**Comment by ALTaleX531** [comment]
Fixed in the latest version.

**Comment by Andrew-Sor** [comment]
> Fixed in the latest version.

Thank you! Of course, I already switched to Windows 11 and everything is fine.
