### ISSUE TITLE
安裝重啟後黑屏

### ISSUE THREAD

**Issue by ScorpionChi** [ALTaleX531/TranslucentFlyouts#76]
![IMG20231116120003](https://github.com/ALTaleX531/TranslucentFlyouts/assets/95428442/1963fcb4-9204-461c-aad7-366ca6bed727)

**Comment by ScorpionChi** [comment]
把硬碟搞廢了，數據全部丟失。

**Comment by ALTaleX531** [comment]
您好，如果遇到TranslucentFlyouts造成其它程序崩溃无法进入桌面的情况，请重启按F8进入安全模式，此时TF将会被强制禁用，此时运行卸载脚本即可解决问题。很遗憾，由于我的延迟回复，没能及时帮助到您，我为TF造成你的文件管理器和桌面异常崩溃感到由衷的抱歉，但请允许我恕不承担误操作造成数据丢失的责任。如果是硬盘格式化造成的数据丢失，您可以使用相关软件恢复绝大部分数据。为了避免该次事故在后来者的身上重演，请您可否提供操作系统的版本号和相关信息，以及一起使用的其它美化软件的列表？你的信息将帮助我更快的定位到问题并进行解决，再次在这里向你表示由衷的歉意！

**Comment by ScorpionChi** [comment]
嘗試過進入安全模式，也是黑屏，不能進行任何操作。
系統是WIN10 22H2專業版，同時在使用的美化軟件Wallpaper Engine。

**Comment by ScorpionChi** [comment]
嘗試過進入安全模式，也是黑屏，不能進行任何操作。 尝试过进入安全模式，也是黑屏，不能进行任何操作。
系統是WIN10 22H2專業版，同時在使用的美化軟件Wallpaper Engine。

**Comment by ScorpionChi** [comment]
嘗試過進入安全模式，也是黑屏，無法進行任何操作。
系統是WIN10 22H2專業版，同時在使用的美化軟體Wallpaper Engine。

**Comment by ScorpionChi** [comment]
進入安全模式後依然是無法做任何操作，都是黑屏。
安裝TF後沒有做任何設置，只是重啟了。系統版本號是build 19045.3693。
沒有使用StartAllBack、ExplorerPatcher等其它軟體。

**Comment by ALTaleX531** [comment]
具体情况是什么呢，是按下Ctrl+Shift+Esc没有反应，且光标没有转动表示加载？
请根据微软的[指引](https://learn.microsoft.com/zh-tw/windows-hardware/manufacture/desktop/windows-recovery-environment--windows-re--technical-reference?view=windows-11)进入WinRE，使用命令提示符调用`del`指令删除TF本体文件，或通过记事本等软件的打开文件对话框，在里面删除本体文件，完成后进入系统再次运行卸载脚本即可

**Comment by ALTaleX531** [comment]
新版加入了足够多的安全措施
