### ISSUE TITLE
ExplorerPatcher的弹出式菜单无法正常显示

### ISSUE THREAD

**Issue by AquaHarp** [ALTaleX531/TranslucentFlyouts#77]
`TranslucentFlyouts`版本2.1.0
`ExplorerPatcher`是从[这里](https://github.com/zetaloop/ExplorerPatcher/releases)下载的汉化版
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/25244319/4f260830-9b3c-4374-9c23-99670254c0a8)

只要点击有弹出式菜单的选项,`ExplorerPatcher`的属性界面会直接消失或无响应。如果关掉`TranslucentFlyouts`,`ExplorerPatcher`的属性界面里的弹出式菜单就能恢复正常显示
下图是正常状态
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/25244319/93b02111-6dfc-46f6-9992-4c2d8cd7dac4)

配置文件
[TranslucentFlyouts.reg.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/13377824/TranslucentFlyouts.reg.txt)
[ExplorerPatcher_22621.2428.59.1.reg.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/13377939/ExplorerPatcher_22621.2428.59.1.reg.txt)

**Comment by ALTaleX531** [comment]
这应该是流利动画造成的问题，之前也有人反馈过，但在不同的机器上表现都不太一样，在我的电脑上不会造成崩溃

**Comment by AquaHarp** [comment]
已解决,将`ExplorerPatcher`更新到22621.2506.60.1官方版即可,(由于官方已提供中文支持,不再使用民间汉化的`ExplorerPatcher`)
