### ISSUE TITLE
Unsupported Windows Build 26002

### ISSUE THREAD

**Issue by hamjin** [ALTaleX531/TranslucentFlyouts#79]
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/30927889/7be04de6-1bca-4858-a80e-ae82c920e1cb)
在升级到Windows 11 Canary 26002之后提示不支持的Windows系统

**Comment by ALTaleX531** [comment]
基本功能应该没有问题，就是可能去除菜单图标背景是用不了了

**Comment by hamjin** [comment]
> 基本功能应该没有问题，就是可能去除菜单图标背景是用不了了

每次开机都会弹出这个窗口，挺不方便的

**Comment by ALTaleX531** [comment]
我会在下个版本解决此问题

**Comment by hamjin** [comment]
close as v3 fixed
