### ISSUE TITLE
Impossible to install under Windos 11 23H2

### ISSUE THREAD

**Issue by 1di9** [ALTaleX531/TranslucentFlyouts#80]
Launching install.bat as administrator results in "Error during the start of TFMain64.dll  Initialisation routine of the dynamic connection library (DLL) failed"

**Comment by 1di9** [comment]
I tried to install X86 version and it works.......however my Winsows 11 is a 64 bit installation....

**Comment by e-t-l** [comment]
> I tried to install X86 version and it works.......however my Winsows 11 is a 64 bit installation....

I installed both versions and I don't see anything working. @1di9 when you say it works, do you mean for all flyouts (e.g. on the desktop)? Or does it only work for 32-bit apps?

**Comment by ALTaleX531** [comment]
Fixed in the latest version.
