### ISSUE TITLE
"HKEY_CURRENT_USER\Software\TranslucentFlyouts\" registry path does not exist (even after reinstalling)

### ISSUE THREAD

**Issue by ark6nz** [ALTaleX531/TranslucentFlyouts#81]
### Issue
"HKCU\Software\TranslucentFlyouts\" registry path does not exist (even after reinstalling).
- Specifically the "TranslucentFlyouts" key.
<img width="256" alt="Registry Screenshot" src="https://github.com/ALTaleX531/TranslucentFlyouts/assets/139096777/fcb7fe17-09d7-4042-89e4-1d78b2bf6cd3">

### Installation
Method of installation:

- Unzipped directory path: `C:\Users\USERNAME\Desktop`

- Installed directory path: `C:\Users\USERNAME\Desktop`

> Yes, I did not install it on the path that was recommended from the README, which was `C:\Program Files`
refer to issue #78 on why I did not install it in the said path.

- [x] Successful installation
- [x] Working after install
- [x] Downloaded [latest release from GitHub repo's Releases](https://github.com/ALTaleX531/TranslucentFlyouts/releases/latest)

### Program version
- Using latest version, particularly [v2.1.0](https://github.com/ALTaleX531/TranslucentFlyouts/releases/tag/v2.1.0)

### Windows build
Edition:	Windows 11 Home Single Language (pls don't judge me I am planning on reinstalling with Pro N)
Version:	22H2
Installed on:	‎3/‎16/‎2023
OS build:	22621.2861
Experience:	Windows Feature Experience Pack 1000.22681.1000.0

### System specs
Processor:	11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz   3.00 GHz
Installed RAM:	8.00 GB (7.70 GB usable)
System type:	64-bit operating system, x64-based processor
Pen and touch:	No pen or touch input is available for this display
Manufacturer:	ASUSTeK COMPUTER INC.

**Comment by ALTaleX531** [comment]
You need to create these registry items manually, therefore I recommend you to use [gui](https://github.com/Satanarious/TransparentFlyoutsConfig/releases/latest).
