### ISSUE TITLE
在资源管理器中右键后滑动，有很大几率导致资源管理器崩溃

### ISSUE THREAD

**Issue by BlackC-Y** [ALTaleX531/TranslucentFlyouts#82]
在资源管理器中右键滑动，有很大几率导致资源管理器崩溃
此电脑窗口好像没问题
19045.3803 同时有使用：枫的工具箱  TranslucentCB

桌面：
![explorer_2023-12-29_00-07-31](https://github.com/ALTaleX531/TranslucentFlyouts/assets/49866610/c38292de-8b7a-45a9-af27-10a9b6714de2)

磁盘窗口中：
![explorer_2023-12-29_00-17-15](https://github.com/ALTaleX531/TranslucentFlyouts/assets/49866610/1d8da2c6-b652-46b1-a969-67491c6a43cb)

**Comment by ALTaleX531** [comment]
v2的工具箱确实有冲突问题，目前我也没想到有什么好的办法...

**Comment by BlackC-Y** [comment]
试了下win11 22621.2861就不会崩溃了，应该是win10的API有问题

**Comment by ALTaleX531** [comment]
还是有冲突的问题，只是不明显了而已，我会在下个版本彻底解决冲突问题
