### ISSUE TITLE
Only seems to work if im dragging an item with right click, and not working from just pressing right click

### ISSUE THREAD

**Issue by lXNine** [ALTaleX531/TranslucentFlyouts#84]
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/155498545/cecf74ba-f56d-4186-924e-5999dcdccdad)
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/155498545/ca86664b-475b-4175-9835-e06d947ba4ec)

**Comment by lXNine** [comment]
It doesnt work when I right click my desktop at all, only when I right click the title bar of google or other programs

**Comment by ALTaleX531** [comment]
duplicate of #11
