### ISSUE TITLE
[UxThemePatcher] An exception thrown while resolving symbol files, some features of TranslucentFlyouts will be limited or unavailable! (hresult: 0x80070002)

### ISSUE THREAD

**Issue by rehansparrow1** [ALTaleX531/TranslucentFlyouts#87]
i thing UxTheme Patcher uses somekind of microsoft service and they stopped that service.
may we should make a small compact package that can all the necessary files for the manipulation of Registration files.

<img width="753" alt="Screenshot 2024-01-10 053912" src="https://github.com/ALTaleX531/TranslucentFlyouts/assets/156163368/0bbbcfc8-8a19-49b9-9d41-14042922fce4">

[UxThemePatcher] An exception thrown while resolving symbol files, some features of TranslucentFlyouts will be limited or unavailable! (hresult: 0x80070002)

**[UxThemePatcher] We tried to download appropriate symbols package from Microsoft server but it failed.
Without symbol files, some features of TranslucentFlyouts may be limited or unavailable, do you want to retry it now? (Y/N)**

**Comment by ALTaleX531** [comment]
Please ensure your internet connection is ok and it has access to the http://msdl.microsoft.com/download/symbols (Microsoft symbol server). (BTW, UxThemePatcher is a sub module of TranslucentFlyouts)

**Comment by akaydev-coder** [comment]
Well I got the same error for a few days. Website is reachable. Strange behavior

**Comment by ALTaleX531** [comment]
So it is same as #66, please wait a few more days.

**Comment by akaydev-coder** [comment]
> So it is same as #66, please wait a few more days.

You're welcome thanks for quick answer. I will test it at the end of the week
Take Care and Stay tuned!
