### ISSUE TITLE
Help, pardon my stupidity but how do i install this?

### ISSUE THREAD

**Issue by ZeZinhuuTheMan** [ALTaleX531/TranslucentFlyouts#9]
I downloaded the zip but i can't find the program to install, i open the text files but do not understand if I'm supposed to write any code directly on the directory or not.

**Comment by thelastlin** [comment]
It seems that don't need to install. 
You can just simply extract the zip archive into the directory you want and then simply execute the `TranslucentFlyoutsGUI.exe` in the extracted directory.

**Comment by aQUICKjoker68** [comment]
Thnx for explaining but there is no .exe like u discribed  in your reply, so what now to do to make this app usefull for a noob like me?

**Comment by thelastlin** [comment]
> Thnx for explaining but there is no .exe like u discribed in your reply, so what now to do to make this app useful...

You may want to:

1. Go to release page of this project(https://github.com/ALTaleX531/TranslucentFlyouts/releases).
2. Find the latest version and download built assert(not source code) like the following example:
![example](https://user-images.githubusercontent.com/20792851/206173937-e07958d5-92ae-4e62-a09c-583a6197ad8b.png)
3. Extract what you downloaded and enjoy it.
