### ISSUE TITLE
Closing explorer window on mouse right click on adress bar

### ISSUE THREAD

**Issue by UnclWish** [ALTaleX531/TranslucentFlyouts#92]
Version 3.0. Windows 10 Pro 22H2 19045.3996
Immersive version installs and launches without errors, but no effect adds.
Win32 version installs, downloads symbols and works, but found a bug: pressing mouse right click on adress bar (where path) of explorer windows didn't show context menu, hangs and after several seconds just close the window. Stopping service solve this.

**Comment by ALTaleX531** [comment]
Immersive version currently cannot work for Windows 10, and the crash issue I think is same as #93 , please wait for the fix.

**Comment by UnclWish** [comment]
Ok. Thanks. I'll wait fix.

**Comment by ALTaleX531** [comment]
Fixed in the latest version.
