### ISSUE TITLE
3.0 issues

### ISSUE THREAD

**Issue by BlackC-Y** [ALTaleX531/TranslucentFlyouts#93]
win32版本 19045.3930 同时有使用：枫的工具箱 TranslucentTB
immersive版本无效

资源管理器地址栏 - 右键崩溃
任务栏托盘图标 原生菜单的话 - 右键崩溃
任务管理器 弹出菜单(文件 选项 查看) - 点击崩溃（会出现任务管理器的设置丢失）

**Comment by ALTaleX531** [comment]
经测试只出现在win10，会在下一个版本中修复，请耐心等待

**Comment by ALTaleX531** [comment]
请查看新版本
