### ISSUE TITLE
Set EffectType separately for dark mode and non-dark mode plz

### ISSUE THREAD

**Issue by xxm101010** [ALTaleX531/TranslucentFlyouts#94]

**Comment by ALTaleX531** [comment]
Can you tell me why you want to have separate `EffectType` for dark mode and light mode? Because I don't really see the need for it....

**Comment by xxm101010** [comment]
maybe Mica better than Acrylic in light mode
dark mod else

**Comment by ALTaleX531** [comment]
You can actually adjust `LightMode_GradientColor` to achieve a much better look than Mica, in the other hand Mica cannot do the same thing and its look is fixed.

**Comment by xxm101010** [comment]
If I'm not mistaken GradientColor has no transparency

**Comment by ALTaleX531** [comment]
GradientColor has transparency, and it is RGBA format.

**Comment by xxm101010** [comment]
ok its working well  thx
