### ISSUE TITLE
symbols应该放到哪里？

### ISSUE THREAD

**Issue by shamodeyu** [ALTaleX531/TranslucentFlyouts#98]
本人原来使用的是2.1版，后来公司不让联网了，但使用正常。

看到3.0版发布后，下载了使用，但软件要求联网下载symbols，因为不能联网，无奈放弃。

但是这时旧版2.1也要求联网下载symbols（是不是3.0把原来的symbols删除了？）

通过symchk工具下载到本机对应的symbols如下，请问应该把它们放到哪个文件夹内，才能让2.1版不再要求联网？
文件夹dwmcore.pdb，下有文件夹4B8DE63029004A74821D91693FFEDDC91，下有文件dwmcore.pdb
文件夹uDWM.pdb，下有文件夹F8DED8A81242403380CC91570B71CBCE1，下有文件uDWM.pdb

**Comment by ALTaleX531** [comment]
答案是卸载脚本会清理掉符号的缓存，确保不会残留任何东西在用户电脑上，其实现在v3可以不联网正常运行。
那几个一长串的文件夹可以复制到 dll所在目录下的symbols子目录，由于TF V2.1开始解析完直接删除本地文件，你需要手动创建symbols目录，我建议先用我修完bug的[版本](https://github.com/ALTaleX531/TranslucentFlyouts/files/14159172/TranslucentFlyouts.Win32.V3.x64.zip)，Release那还没发，因为我想更新更多内容再发。
虽然但是，这不是个好办法，因为系统更新肯定会导致再次下载符号，我建议一劳永逸，禁用所有需要符号的功能并进入兼容性模式，以下是一个可以直接导入的[注册表文件](https://github.com/ALTaleX531/TranslucentFlyouts/files/14159185/disable_internet_connection.zip)

**Comment by ALTaleX531** [comment]
我刚刚才注意到你的符号下载脚本来自于DwmBlurGlass，这两个项目使用的符号文件是不一样的，TF需要的符号文件为uxtheme.pdb，shell32.pdb，你下载的符号无法被TF使用，我建议尝试使用我之前提供的注册表导入脚本

**Comment by shamodeyu** [comment]
谢谢，导入脚本后不再弹窗了。
