### ISSUE TITLE
与ExplorerPatcher不兼容：右键任务栏崩溃

### ISSUE THREAD

**Issue by SAFEluren** [ALTaleX531/TranslucentFlyouts#99]
如题，ExplorerPatcher与本项目运行时，右键任务栏Explorer会发生崩溃。
在ExplorerPatcher的属性页面里面也没有看到被正确渲染，停止运行本项目后，右键任务栏的行为不会发生崩溃。
TranslucentFlyouts版本为v3.0.0

![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/79032826/aa7188f6-d224-4b27-a86c-c8534a87e3b0)

**Comment by ALTaleX531** [comment]
#98 里有修复的版本，你可以先用着那个版本先

**Comment by ALTaleX531** [comment]
请查看新版本
